= Whitebox overall system

The interfaces show how the components interact with each other and which interfaces the IRS is providing.

== Component diagram

[plantuml, target=whitebox-overview, format=png]
....
@startuml
skinparam monochrome true
skinparam shadowing false
skinparam spacing 50


component [**IRSApplication**] <<System>> {
	component [**IRS**] <<System>> as IRS
	component [**AAS Wrapper**] <<System>> as AAS_W
	component [**EDC Consumer**] <<System>> as EDC

}

component [**CatenaX-Network**] <<CX-Environment>> {
    component [**IAM/KeyCloak**] <<System>> as IAM_IRS
    component [**Digital Twin Registry**] <<System>> as DT_REG
    component [**IAM/DAPS**] <<System>> as IAM_DAPS
    IAM_IRS --[hidden]> DT_REG
    DT_REG --[hidden]>  IAM_DAPS
}

component [**Tier/OEM**] <<Tier/OEM-Environment>> {

    component [**EDC_Provider_OEM**] <<System>> as EDCProviderOEM
    component [**EDC_Provider_Tier1**] <<System>> as EDCProviderTier1
    component [**EDC_Provider_Tier1.1**] <<System>> as EDCProviderTier11
    component [**SubmodelServer_OEM**] <<System>> as SubmodelServerOEM
    component [**SubmodelServer_Tier1**] <<System>> as SubmodelServerTier1
    component [**SubmodelServer_Tier1.1**] <<System>> as SubmodelServerTier11
}


actor IrsApiConsumer

IrsApiConsumer -right(0- IRS
IrsApiConsumer <.r.> IAM_IRS
IRS <.d.> AAS_W
IRS <.l.> IAM_IRS
AAS_W <..> EDC
IRS <.> DT_REG
EDC <..> IAM_DAPS
EDC <..> EDCProviderOEM
EDC <...> EDCProviderTier1
EDC <....> EDCProviderTier11
IAM_DAPS <..> EDCProviderOEM
IAM_DAPS <...> EDCProviderTier1
IAM_DAPS <....> EDCProviderTier11
EDCProviderOEM <..> SubmodelServerOEM
EDCProviderTier1 <..> SubmodelServerTier1
EDCProviderTier11 <..> SubmodelServerTier11

@enduml
....

== Component description

|===
|Components |Description

|IRSApiConsumer
|Proxy for any consumer of the IRS api.

|IRS
|The IRS consumes relationship information across the CX-Network and builds the graph view. Within this Documentation, the focus lies on the IRS

|AAS Wrapper
|The AAS Wrapper is a System, which simplifies the communication with the EDC and wraps the communication.

|AAS Proxy
|The AAS Proxy is a System, which enables the consumer to simplify the communication with other CX Partners.

|EDC Consumer
|The EDC Consumer Component is there to fulfill the GAIA-X and IDSA-data sovereignty principles. The EDC Consumer consists out of a control plane and a data plane.

|EDC Provider
|The EDC Provider Component connects with EDC Consumer component and  forms the end point for the actual exchange of data. It handles automatic contract negotiation and the subsequent exchange of data assets for connected applications.

|Submodel Server
|The Submodel Server offers endpoints for requesting the Submodel aspects.

|IAM/DAPS
|DAPS as central Identity Provider
|===