@startuml
skinparam monochrome true
skinparam shadowing false

autonumber "<b>[000]"

actor "Client" as User

box "Tier" #LightGrey
participant ESRCertificateStatisticSubmodelServer as ESRSubServer
participant IRS as IRS
participant MinIO as MinIO
participant "EDCConsumer" as EDCConsumer #99FF99
end box



User --> ESRSubServer: ../esr-certificate
note left
params: {globalAssetId, bomLifecycle, certificateName}
end note
ESRSubServer -> IRS : POST /irs/jobs
ESRSubServer <-- IRS : 201 ok jobId
note left
params: {globalAssetId, bomLifecycle, depth=1}
end note
ref over IRS, DTRegistry, DAPS, "SubmodelServer AssemblyPartRelationship)"
    Process JobResponse for given params
end ref

loop 100 times
    ESRSubServer --> IRS: GET /irs/jobs?states=COMPLETED
    ESRSubServer <-- IRS: jobList
    alt jobId is in jobList
        ESRSubServer --> IRS: GET /irs/jobs{jobId}
        ESRSubServer <-- IRS: return JobResponse
        ESRSubServer --> ESRSubServer: break loop
     else
        ESRSubServer -> ESRSubServer : wait 5000
    end alt
end loop
opt not hasCompleted(job)
    User <--  ESRSubServer : 4xx
end opt
ref over  ESRSubServer
    ESRSubServer --> ESRSubServer : BPNL number / SupplyOnRequest
end ref

@enduml