= Development concepts

== Build, test, deploy
The IRS is built using https://maven.apache.org/[Apache Maven] and utilizes all the standard concepts of it.
Test execution is part of the build process and a minimum test coverage of 80% is enforced.

The project setup contains a multi-module Maven build.
Commonly used classes (like the IRS data model) should be extracted
into a separate submodule and reused across the project.
However, this is not a "one-size-fits-all" solution.
New submodules should be created with care and require a review by the team.

The Maven build alone only leads up to the JAR artifact of the IRS.
To create Docker images, the Docker build feature is used.
This copies all resources into a builder image,
builds the software and creates a final Docker image at the end that can then be deployed.

Although the Docker image can be deployed in various ways, the standard solution are the provided Helm charts,
which describe the required components as well.

== Code generation
There are two methods of code generation in the IRS:

=== Lombok
The https://projectlombok.org/[Lombok] library is heavily used to generate boilerplate code
(like Constructors, Getters, Setters, Builders...).
This way, code can be written faster and this boilerplate code is excluded from test coverage,
which keeps the test base lean.

=== Swagger / OpenAPI
The API uses https://www.openapis.org/[OpenAPI] annotations to describe the endpoints with all necessary information.
The annotations are then used to automatically generate the OpenAPI specification file,
which can be viewed in the Swagger UI that is deployed with the application.

The generated OpenAPI specification file is automatically compared to a fixed,
stored version of it to avoid unwanted changes of the API (see `IrsApplicationTests.generatedOpenApiMatchesContract`).

== Migration
There currently is no data migration mechanism for the IRS.
In case the model of the persisted data (Jobs) changes, data is dropped and Jobs will need to be recreated.

== Configurability
The IRS utilizes the configuration mechanism provided by https://spring.io/projects/spring-boot[Spring Boot.]
Configuration properties can be defined in the file `+src/main/resources/application.yml+`

For local testing purposes, there is an additional configuration file called `+application-local.yml+`.
Values can be overriden there to support the local dev environment.

Other profiles should be avoided.
Instead, the configuration can be overwritten using
https://docs.spring.io/spring-boot/docs/3.1.9/reference/htmlsingle/#features.external-config[Spring's external configuration mechanism].
The operator must have total control over the configuration of the IRS.

