@startuml
participant IRS
participant DiscoveryService
participant "EDC Provider" as EDCProvider
participant "DTR 1" as DTR1
participant "DTR 2" as DTR2

IRS ->> DiscoveryService: Get EDCs for BPN
DiscoveryService ->> IRS: Return list of 1 EDC
IRS ->> EDCProvider: Query for DTR contract offer
EDCProvider ->> IRS: 2 DTR contract offers

par
    group Query DTR 1
        IRS ->> EDCProvider: Negotiate contract
        IRS ->> DTR1: Query for DT
        DTR1 ->> IRS: no DT
    end

    else

    group Query DTR 2
        IRS ->> EDCProvider: Negotiate contract
        IRS ->> DTR2: Query for DT
        DTR2 ->> IRS: DT
    end
end
@enduml