= Operational concepts

== Administration

=== Configuration
The IRS can be configured using two mechanisms:

==== application.yml
If you build the IRS yourself, you can modify the application.yml configuration file that comes with the IRS. This file contains all possible configuration values for the application.
Once the Docker image is built, these values can only be overwritten using the Spring external config mechanism (see https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html), e.g. by mounting a config file in the correct path or using environment variables.

==== Helm Chart
The most relevant configuration properties are exposed as environment variables and need to be set in the Helm chart for the application to run at all. Check the IRS Helm chart in Git for all available variables.

== Disaster-Recovery

=== Ephemeral components
All components in the IRS deployment that are not listed in the persistent components section below are considered ephemeral and can be replaced easily in a disaster scenario.
All deployment components are described using Helm charts, which can be used to restore the deployment with the Docker images.
If the Docker images go missing, they can be restored by running the build pipelines for the corresponding version tag of the component.

=== Persistent components
These components utilize data persistence, which needs to be backed up separately by the operator.

- *Minio persistent volume*: Contains the stored Job information. In the event of data loss, Jobs can be restarted to retrieve the data from the network.
- *Prometheus persistent volume*: Contains the IRS monitoring data. In case of data loss, no analysis can be done for past timeframes.
- *Vault secrets*: In case of data loss, the credentials stored in the Vault need to be manually recreated. See the deployment view for an overview.

== Scaling
If the number of consumers raises, the IRS can be scaled up by adding more resources for the Deployment Pod. These resources can be used to utilize more parallel threads to handle Job execution.

== Clustering
The IRS can run in clustered mode as each running job is only present in one pod at a time.
Note: Once a resume feature is implemented, this needs to be addressed here.

== Logging
Logs are written directly to stdout and picked up by cluster management.

== Monitoring
The application can be monitored using Prometheus and Grafana. Both systems are defined in the Helm charts with a default setup.
A number of Grafana dashboards are automatically deployed to display data on:

- Pod / JVM resources
- API metrics
- Functional information about IRS Jobs