= Safety and security concepts

== Authentication / Authorization

=== IRS API

The IRS is secured using OAuth2.0 / Open ID Connect.
Any request to the IRS API requires a valid bearer token.
The JWT token should also contain two claims:

- 'bpn' which is equal to the configuration value from the `API_ALLOWED_BPN` property
- 'resource_access' with the specific key 'Cl20-CX-IRS' for C-X environments. (The keys are configurable. For more details see chapter "IRS OAuth2 JWT Token").
The list of values will be converted into roles by IRS.
Currently, the IRS API handles two roles: *'admin_irs'* and *'view_irs'.* A valid token with the *'admin_irs'* role can access any endpoint exposed by the IRS API, while a token with the *'view_irs'* role does not have access to policy endpoints and can only operate on resources it owns.
This means that it can only access the resources that it created, e.g. jobs and batches.
This behaviour is shown in the table below.

==== Rights and Roles Matrix of IRS

|===
| Category         | Action            | Endpoint                        | view_irs   | admin_irs
| Policy Store     | Add policy        | POST /irs/policies              |            | x
|                  | Get policies      | GET /irs/policies               |            | x
|                  | Update policy     | PUT /irs/policies/{policyId}    |            | x
|                  | Delete policy     | DELETE /irs/policies/{policyId} |            | x
| Aspect models    | Get aspect models | GET /irs/aspectmodels           |  x         | x
| Job processing   | Register job      | POST /irs/jobs                  |  x        | x
|                  | Get jobs          | GET /irs/jobs                   |  x        | x
|                  | Get job           | GET /irs/jobs/{jobId}           |  x        | x
|                  | Cancel job        | PUT /irs/jobs/{jobId}           |  x        | x
| Batch processing | Register order    | POST /irs/orders                |  x        | x
|                  | Get order         | GET /irs/orders/{orderId}       |  x        | x
|                  | Cancel order      | PUT /irs/orders/{orderId}       |  x        | x
|                  | Get batch         | GET /irs/orders/{orderId}/batches/{batchId}  | x    | x
| Environmental- and
Social Standards   | Register investigation job | POST /ess/bpn/investigations        | x    | x
|                  | Get investigation job      | GET /ess/bpn/investigations{id}     | x    | x
|                  | Accept notifications       | POST /ess/notification/receive      | x      | x
|===

Legend: x = full access to all resources

=== IRS as DTR client

The IRS acts as a client to the Digital Twin Registry (DTR), which is also secured using OAuth2.0 / Open ID Connect.

The IRS uses client credentials to authenticate requests to the DTR.
This requires the IRS account to have access to every item in the DTR, regardless of the permissions of the account calling the IRS API.

=== IRS as decentralized DTR client

In a decentralized network, the IRS uses the EDC client to access the provider DTR.
This way, no authentication other than the EDC contract negotiation, is required to access the DTR.

=== IRS as EDC client

The IRS accesses the Catena-X network via the EDC consumer connector.
This component requires authentication via a Verifiable Credential (VC), which is provided to the EDC via the Managed Identity Wallet.

The VC identifies and authenticates the EDC and is used to gain access rights to the data transferred via the EDC.

== Credentials

Credentials must never be stored in Git!



