= Scenario 3: Request for JobResponse

[plantuml, target=request-job, format=png]
....
@startuml
skinparam shadowing false
autonumber "<b>[000]"

actor IrsApiConsumer
activate IrsApiConsumer


box "IRSApplication" #LightGrey
participant IrsAPI
activate IrsAPI
participant IrsController
activate IrsController
participant IrsItemGraphQueryService
activate IrsItemGraphQueryService
participant PersistentJobStore
activate PersistentJobStore

IrsApiConsumer -> IrsAPI : GET /irs/jobs/:jobId
IrsAPI -> IrsController :  getJobById
IrsController -> IrsItemGraphQueryService :  getJobForJobId
IrsItemGraphQueryService -> PersistentJobStore: find
opt jobNotFound
    IrsController <-- IrsItemGraphQueryService : error - not found
    IrsAPI <-- IrsController : error - not found
    IrsApiConsumer <-- IrsAPI : 404 - not found
else jobFound
    IrsItemGraphQueryService <-- PersistentJobStore: job details
    IrsItemGraphQueryService -> IrsItemGraphQueryService : build job response
    opt jobFinished or includePartialResults=true
        IrsItemGraphQueryService -> PersistentJobStore : fetch job payload data
        IrsItemGraphQueryService <-- PersistentJobStore
    end opt
    IrsController <-- IrsItemGraphQueryService : job details
    IrsAPI <-- IrsController : job details
    IrsApiConsumer <-- IrsAPI : job details
end opt


@enduml
....

== Overview

When a user requests job details, the IRS looks up the jobId in the persistent job store. If the job exists, it will proceed to fetch the job details and prepare a response object.
Only if the job is in state "COMPLETED" or if the caller has set the parameter "includePartialResults" to true, the IRS will fetch the payload data for the job (relationships, AAS shells and submodels, if applicable) and attach it to the response object.

This will then be passed to the caller.