@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20
skinparam defaultFontName "Architects daughter"

node ArgoCD
node GitHub
node "Docker Hub" as docker
node "Kubernetes Cluster" as k8s
node "HashiCorp Vault" as vault
actor Operator as ops

ops --> ArgoCD : create app deployment
ops --> vault : store credentials
ArgoCD --> GitHub : fetch Helm charts
ArgoCD --> k8s : create resources
ArgoCD -> vault : fetch credentials
GitHub --> docker : push Docker image
k8s --> docker : fetch Docker image
@enduml