@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20
skinparam defaultFontName "Architects daughter"

cloud "Digital Twin Registry" as dtr
cloud "EDC Providers" as providers
cloud OAuth2
cloud "HashiCorp Vault" as vault

node "IRS Kubernetes Cluster" as k8s {

    component IRS
    component Minio
    component "EDC Consumer" as consumer
    database "Consumer DB" as cdb

    IRS --> Minio
    IRS --> consumer
    cdb - consumer

}

IRS -> OAuth2
providers -- dtr
consumer -- providers
consumer -- vault

@enduml