@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20
skinparam defaultFontName "Architects daughter"

cloud OAuth2

node "Kubernetes Cluster" as k8s {

    component IRS
    component Minio
    component "Decentral Digital Twin Registry" as dtr
    component "EDC Consumer" as consumer
    component "EDC Provider" as provider
    component "Managed Identity Wallet" as miw
    collections "Submodel Provider" as submodel


    IRS --> Minio
    IRS -> consumer
    consumer --> miw
    provider --> miw
    consumer <--> provider
    provider --- submodel
    provider --- dtr

}

IRS --> OAuth2

@enduml