@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho


node "Kubernetes Cluster" as k8s {

    package "Consumer Side" {
        component IRS
        component Minio
        component "EDC Consumer" as consumer
    }

    package "Provider Side" {
        component "EDC Provider" as provider
        collections "Provider Backend" as submodel
        component "Decentral Registry" as dtr
    }

    component OAuth2
    component "Managed IdentityWallet" as MIW

    component "Discovery Service" as ds
    component "Semantic Hub" as semHub
    component "IRS Debugging Frontend" as frontend

    IRS --> Minio
    IRS --> consumer
    IRS --> ds

    MIW ---> provider
    MIW ---> consumer

    provider <-> consumer

    provider -- submodel
    provider -- dtr

    OAuth2 ---> ds
    OAuth2 ---> IRS
    OAuth2 ---> semHub

    IRS -> semHub
    IRS -> frontend
}

@enduml