@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20
skinparam defaultFontName "Architects daughter"

node IRS <<app>> {

    frame public {
        agent ingress
        interface HTTPS
    }

    frame internal {
        node pod {
            artifact "IRS Docker image"
        }
        agent service as svc
        collections secrets
        interface "Actuator API (Port 4004)" as actuator
    }


    ingress #-- HTTPS
    svc #- ingress : IRS API (Port 8080)
    pod #--- svc
    svc #-- actuator
    pod -- secrets

}


@enduml