@hostname = localhost
@port = 6181
@host = {{hostname}}:{{port}}
@contentType = application/json
@idsEndpoint = /api/v1/ids/data
@headerName = X-Api-Key
@headerValue = password


### Get Ids data
# @name ids

GET http://{{host}}{{idsEndpoint}} 
{{headerName}}: {{headerValue}}
Content-Type: {{contentType}}

