server:
  port: 8081

spring:
  application:
    name: broker-proxy
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

management:
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, kafka, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 4005

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    net.catenax.brokerproxy: INFO

springdoc:
  api-docs:
    path: /broker-proxy/api-docs
  swagger-ui:
    path: /broker-proxy/swagger-ui
  writer-with-order-by-keys: true

brokerproxy:
  apiUrl: http://localhost:8081
  kafkaTopic: catenax_events


