@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName "Architects daughter"


actor IrsApiConsumer
actor EssApiConsumer
actor PolicyStoreApiConsumer

component [**Digital Twin Registry**] <<System>> as DTR
component [**EDC**] <<System>> as EDC

component [**IRS-Application**] <<System>> as IRS {
    component [**RecursiveJobHandler**] <<Component>> as RecursiveJobHandler
    component [**IrsController**] <<Component>> as IrsController
    component [**PolicyStoreController**] <<Component>> as PolicyStoreController
    component [**EssController**] <<Component>> as EssController
    component [**JobOrchestrator**] <<Component>> as JobOrchestrator
    component [**TransferProcessManagement**] <<Component>> as TransferProcessManagement

    port "API" as API_PORT
    port "Digital Twin Client" as AAS_PORT
    port "EDC Client" as EDC_PORT
    () "BlobStore Interface" as StoreInterface

    IrsController <..> JobOrchestrator
    JobOrchestrator <..> TransferProcessManagement
    JobOrchestrator <..> RecursiveJobHandler
    TransferProcessManagement -( StoreInterface
    PolicyStoreController -( StoreInterface
    EssController <..> JobOrchestrator
}





IrsController -up- API_PORT
PolicyStoreController -down- API_PORT
EssController -down- API_PORT
IrsApiConsumer --down(0- API_PORT
EssApiConsumer --down(0- API_PORT
PolicyStoreApiConsumer --(0- API_PORT

TransferProcessManagement --right-- AAS_PORT
TransferProcessManagement --right-- EDC_PORT

AAS_PORT -up-(0 DTR
EDC_PORT -up-(0 EDC

database "BlobStore" as BlobStore
StoreInterface -down- BlobStore
@enduml