@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
skinparam defaultFontName "Architects daughter"


 component [**IRS-Application**] <<System>> as IRS {
    component [**RecursiveJobHandler**] <<Component>> as RecursiveJobHandler
    component [**IrsController**] <<Component>> as IrsController
    component [**PolicyStoreController**] <<Component>> as PolicyStoreController
    component [**EssController**] <<Component>> as EssController
    component [**IrsItemGraphQueryService**] <<Component>> as IrsItemGraphQueryService
    component [**JobOrchestrator**] <<Component>> as JobOrchestrator
    component [**TransferProcessManagement**] <<Component>> as TransferProcessManagement
    component [**PolicyStore**] <<Component>> as PolicyStore
    component [**EssService**] <<Component>> as EssService
    component [**EssRecursiveNotificationHandler**] <<Component>> as EssRecursiveNotificationHandler


    port "IRS API" as API_PORT
    port "Digital Twin Client" as AAS_PORT
    port "EDC Client" as EDC_PORT

    () "BlobStore\nInterface" as StoreInterface


    IrsController <..> IrsItemGraphQueryService
    IrsItemGraphQueryService <..> JobOrchestrator
    JobOrchestrator <..> TransferProcessManagement
    JobOrchestrator <..> RecursiveJobHandler
    TransferProcessManagement --( StoreInterface
    PolicyStore -( StoreInterface
    PolicyStoreController <.> PolicyStore
    EssController <..> EssService
    EssService <..> IrsItemGraphQueryService
    EssService <..> EssRecursiveNotificationHandler

}
component [**Digital Twin Registry**] <<System>> as DTR
component [**EDC**] <<System>> as EDC
actor IrsApiConsumer
IrsController -up- API_PORT
PolicyStoreController -down- API_PORT
EssController -down- API_PORT
IrsApiConsumer -(0- API_PORT


TransferProcessManagement --- AAS_PORT
TransferProcessManagement --- EDC_PORT
AAS_PORT --right-(0 DTR
EDC_PORT --right-(0 EDC

database "BlobStore" as BlobStore
StoreInterface -down- BlobStore

@enduml