@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 100
skinparam linetype ortho
skinparam defaultFontName "Architects daughter"


component [**TransferProcessManagement**] <<Component>> as TransferProcessManagement {
    component [**AASTransferProcessManager**] <<Component>> as TransferProcessManager
    component [**DigitalTwinRegistryFacade**] <<Component>> as DTRFacade {
        component [**DigitalTwinRegistryClient**] <<Component>> as DTRClient
    }
    component [**SubmodelFacade**] <<Component>> as SubmodelFacade {
        component [**SubmodelClient**] <<Component>> as SubmodelClient
    }
    component [**ExecutorService**] <<Component>> as ExecutorService
}

node "Digital Twin Registry" {
    [**AAS Registry**] <<Component>> as AASR
}

node "SubmodelServer" {
    [**SubmodelServer**] <<Component>> as SMS
}


DTRFacade --0)- TransferProcessManager
SubmodelFacade --0)- TransferProcessManager
ExecutorService <...> TransferProcessManager

interface "Registry API" as RegAPI
RegAPI -- AASR
DTRClient ----( RegAPI


interface "SubmodelAPI" as SMSAPI
SMSAPI -- SMS
SubmodelClient ----( SMSAPI

database BlobStore
TransferProcessManager -left-( BlobStoreInterface
BlobStoreInterface <...> BlobStore
@enduml