@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 100
skinparam linetype ortho
skinparam defaultFontName "Architects daughter"


component [**TransferProcessManagement**] <<Component>> as TransferProcessManagement {
    component [**AASTransferProcessManager**] <<Component>> as TransferProcessManager
    component [**DecentralDigitalTwinRegistryService**] <<Component>> as DTRService {
        component [**DecentralDigitalTwinRegistryClient**] <<Component>> as DTRClient {
            component [**EndpointDataForConnectorsService**] <<Component>> as EndpointDataForConnectorsService
        }
    }
    component [**EdcSubmodelFacade**] <<Component>> as SubmodelFacade {
        component [**EdcSubmodelClient**] <<Component>> as SubmodelClient {
            component [**ContractNegotiationService**]  <<Component>> as ContractNegotiationService {
                [**PolicyCheckerService**] <<Component>> as PolicyCheckerService
            }
        }
    }
    component [**ExecutorService**] <<Component>> as ExecutorService
}

node PolicyStore {
    [**PolicyStoreService**] <<Component>> as PolicyStoreService
}

node "Digital Twin Registry" {
    [**AAS Registry**] <<Component>> as AASR
}

node "SubmodelServer" {
    [**SubmodelServer**] <<Component>> as SMS
}

DTRService --0)- TransferProcessManager
SubmodelFacade --0)- TransferProcessManager
ExecutorService <...> TransferProcessManager

interface "Registry API" as RegAPI
RegAPI -- AASR
DTRClient ----( RegAPI


interface "SubmodelAPI" as SMSAPI
SMSAPI -- SMS
SubmodelClient ----( SMSAPI
interface "PolicyStoreAPI" as PolicyStoreAPI
PolicyCheckerService --(  PolicyStoreAPI
PolicyStoreAPI -- PolicyStoreService
EndpointDataForConnectorsService -> SubmodelFacade

database BlobStore
TransferProcessManager -left-( BlobStoreInterface
BlobStoreInterface <...> BlobStore
@enduml