@startuml
skinparam monochrome true
skinparam shadowing false
skinparam spacing 50


package [**IRS-Application**] <<IRS System>> as irs_component {
	component [**IRS**] <<System>> as IRS
	component [**EDC (Consumer)**] <<System>> as EDC
}

package [**CatenaX-Network**] as network {
    component [**Managed Identity Wallet**] <<System>> as miw
    component [**IAM/KeyCloak**] <<System>> as IAM_IRS
    component [**EDC Discovery**] <<System>> as edc_discovery
    component [**Discovery Finder**] <<System>> as discovery_finder
    component [**Semantic Hub**] <<System>> as semantic_hub
    component [**BPDM**] <<System>> as bpdm
    miw -[hidden]d- IAM_IRS
    miw -[hidden]r- discovery_finder
    discovery_finder -[hidden]d- edc_discovery
    bpdm -[hidden]d- semantic_hub
}

package [**OEM/N-Tier**] <<CatenaX Data Provider Company>> as provider {
    component [**EDC (Provider)**] <<System>> as EDCProvider
    component [**SubmodelServer**] <<System>> as SubmodelServer
    component [**Digital Twin Registry**] <<System>> as DT_REG
    EDCProvider <--> SubmodelServer
    EDCProvider <--> DT_REG
}

actor IrsApiConsumer

IrsApiConsumer -right(0- IRS
IrsApiConsumer <.r.> IAM_IRS
IRS <.d.> EDC
IRS <..> IAM_IRS
IRS <..> edc_discovery

IRS <..> discovery_finder
IRS <..> semantic_hub
IRS <..> bpdm
EDC <..> miw
EDC <..> EDCProvider
miw <..> EDCProvider

@enduml