{
 "title": "Resource Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "System CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Average Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage in Byte",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pool Size Thread",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "executor_pool_size_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" },
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "__auto" },
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}