@startuml
title IRS API sequence diagramm v0.2

actor CE as "CE Dashboard"

box Item Relationship Service
participant IRS_API as " API v0.2"
end box


autonumber "<b> [00]"

CE -> IRS_API: GET /irs/item/{globalAssetId}
activate IRS_API

IRS_API --> CE: HTTP 202 : Status json
IRS_API --> CE: HTTP 4xx : 
deactivate IRS_API


CE -> IRS_API: GET /irs/item/{globalAssetId}
activate IRS_API
IRS_API --> CE: HTTP 202 : Status json + current Payload

deactivate IRS_API

@enduml