@startuml 
skinparam monochrome true
skinparam shadowing false

[**IRS**] <<System>> as IRS

[**AAS Wrapper / AAS Proxy**] <<Component>> as AASW


node "Digital Twin Registry" {
    [**AAS Registry**] <<Component>> as AASR
}

node "Group of Submodel Endpoints" {
  [**Submodel-Server**] <<Component>> as SN
}
actor Consumer
interface "IRS API" as IAPI
interface "AASProxyAPI" as IAASW
interface "IRegistryAPI" as IRAPI
interface "ISubmodelAPI" as ISubModelAPI

Consumer -( IAPI
IAPI - IRS
IAASW - AASW
IRS -( IAASW
IRAPI - AASR
AASW --( IRAPI
ISubModelAPI - SN
AASW -( ISubModelAPI


@enduml