@startuml 
skinparam monochrome true
skinparam shadowing false

[\n IRS \n] <<System>> as IRS

[\n AAS Wrapper / AAS Proxy \n] <<Component>> as AASW
[\n AAS Resgistry \n] <<Component>> as AASR

node "Group of Submodel Endpoints" {
  [\n Submodel-Server \n] <<Component>> as SN
}

interface "IRS API" as IAPI

IAPI - IRS
IRS . AASW
AASW . AASR
AASW .. SN

@enduml