@startuml
class MultiTransferJob {
--
* jobId : string (UUID)
* transferProcessIds: Set<string>
* state : JobState
* jobData: Map<String, String>
* errorDetail: string
* completedTransfers: List<TransferProcess>
}

MultiTransferJob -> JobState


enum JobState {
    UNSAVED,
    INITIAL,
    IN_PROGRESS,
    TRANSFERS_FINISHED,
    COMPLETED,
    ERROR;
}

class  TransferProcess {
* String id;
* Type type = Type.CONSUMER;
* int state;
* int stateCount = TransferProcessStates.UNSAVED;
* long stateTimestamp;
* String errorDetail;
* DataRequest dataRequest;
* ResourceManifest resourceManifest;
* ProvisionedResourceSet provisionedResourceSet;
}

class DataRequest{
 id : String
 processId : String
 connectorAddress : String
 protocol : String
 connectorId : String
 dataEntry : DataEntry
 dataDestination : DataAddress
 managedResources : boolean (true)
 properties : Map<String, String>
 * transferType : TransferType

}
TransferProcess -> TransferProcessStates

class DataEntry {
    id : String
    policyId : String
    catalogEntry : DataCatalogEntry
}

interface DataCatalogEntry {
    dataAddress : DataAddress
}


class TransferType {
    ..
}

enum TransferProcessStates {
    UNSAVED
}

MultiTransferJob -> TransferProcess
DataRequest -> DataEntry
DataEntry -> DataCatalogEntry
DataRequest -> TransferType
TransferProcess -> DataRequest
@enduml