@startuml
'https://plantuml.com/component-diagram


package "IRS" {

  component  [Web Server] #Yellow
  [ConsumerApiController]
  [ConsumerService]
  ConsumerApiController -> ConsumerService : retrievePartsTree(request)
  BlobstoreAPI - [BlobstoreAPIImpl]

  ConsumerService -> BlobstoreAPI : createContainer(storageAccountName, containerName)
  [JobOrchestrator]
  ConsumerService -> JobOrchestrator : uses
  BlobstoreAPIImpl ..> API : use
  JobStore -  [InMemoryJobStore]
  JobOrchestrator ..> JobStore : create(job)

  RecursiveJobHandler - [PartsTreeRecursiveJobHandler]
  JobOrchestrator ..> RecursiveJobHandler: initiate(job)

  TransferProcessManager - [TransferProcessManagerImpl]
  JobOrchestrator ..> TransferProcessManager: initiateConsumerRequest(dataRequest)

  JobOrchestrator --> [JobTransferCallback]
}


package "Blobstore" {
  API - [BlobstoreDriver]

}

database Blobstore {
}


@enduml