{
 "title": "Outbound Requests",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Roundtrip time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_client_requests_seconds_bucket{client_name=\"irs-aas-registry.dev.demo.catena-x.net\"}[$__interval]))",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "sum by(le) (increase(http_client_requests_seconds_bucket{client_name=\"aaswrapper\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total error responses by client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum by(client_name) (increase(http_client_requests_seconds_count{outcome=\"SERVER_ERROR\"}[100y])), 1)",
     "legendFormat": "{{client_name}} 5xx"
    },
    {
     "expr": "round(sum by(client_name) (increase(http_client_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[100y])), 1)",
     "legendFormat": "{{client_name}} 4xx"
    }
   ]
  },
  {
   "title": "Request duration by client (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client_name) (rate(http_client_requests_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_retries_total[100y])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Number of timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(http_requests_timeouts_total[100y])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}