{
 "title": "IRS-Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Job Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_created_total[100y])"
    }
   ]
  },
  {
   "title": "Total Completed Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_jobstate_sucessful_total[100y])"
    }
   ]
  },
  {
   "title": "Total Running Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"running\"}"
    }
   ]
  },
  {
   "title": "Process Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(increase(job_execution_time[100y]))"
    },
    {
     "expr": "min(increase(job_execution_time[100y]))"
    },
    {
     "expr": "max(increase(job_execution_time[100y]))"
    },
    {
     "expr": "avg(quantile(0.5, job_execution_time))"
    }
   ]
  },
  {
   "title": "Total Cancelled Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(jobs_jobstate_cancelled_total{jobstate=\"cancelled\"}[100y]), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs currently in JobStore",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstore{jobstate=\"jobs_in_store\"}"
    }
   ]
  },
  {
   "title": "Total Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase({jobstate=\"failed\"}[100y]), 1)"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    { "expr": "jobs_snapshot_success", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_running", "legendFormat": "{{label_name}}" },
    { "expr": "jobs_snapshot_cancelled", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Time per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "increase(job_execution_time[1m])"
    }
   ]
  },
  {
   "title": "Process Time per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "increase(job_execution_time[1h])"
    }
   ]
  },
  {
   "title": "Snapshot Stat",
   "type": "stat",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_snapshot_success", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_running", "legendFormat": "{{label_name}}" },
    { "expr": "jobs_snapshot_cancelled", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_failed", "legendFormat": "__auto" }
   ]
  }
 ]
}