@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

autonumber "<b>[000]"

participant "Client App (Script)" as Client

box "OEM" #LightGrey
    participant IRS as IRS
    participant SubmodelServer as SubmodelServer
    participant dDTR as dDTR
    participant EDC as EDC #99FF99
end box


box SharedServices
    participant DiscoveryFinder as DiscoveryFinder
    participant EDCDiscoveryService as EDCDiscoveryService
end box


loop array of aasIdentifier
    Client -> IRS : [hidden] GET /irs/proxy/registry/shell-descriptors/{aasIdentifier}/{bpn}
    ref over IRS, DiscoveryFinder, EDCDiscoveryService, EDC, dDTR
        create collection of {aasIdentifier}

        registry/shell-descriptors/{aasIdentifier} for given BPN
        collection.add({aasIdentifier})
    end
end loop


Client <-- IRS : return array of {aasIdentifier}

Client -> Client :  filter aas for submodelDescriptor  (asPlanned)
        note right
               semanticId/
                    ["type"="ExternalReference"]/
                        keys["type"="GlobalReference"]/
                            ["value".contains("SingleLevelBomAsPlanned")]
               SingleLevelBomAsPlanned (only downwards supported!!)
        end note

opt aas is asPlanned

     Client -> Client : add aas to aasResultSet
     note right
                 Requesting all twins for a given "bomLifecycle"
     end note

end opt

Client <-- Client : aasResultSet


@enduml