@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

autonumber "<b>[000]"

participant "Client App (Script)" as Client

box "OEM" #LightGrey
    participant IRS as IRS
    participant SubmodelServer as SubmodelServer
    participant dDTR as dDTR
    participant EDC as EDC #99FF99
end box


participant EDC as EDCTier1

box "Tier 1"
     participant IRS as IRSTier1
     participant SubmodelServer as SubmodelServerTier1
     participant dDTR as dDTRTier1
     participant EDC as EDCConsumerTier1 #99FF99
end box

box SharedServices
    participant DiscoveryFinder as DiscoveryFinder
    participant EDCDiscoveryService as EDCDiscoveryService
end box

Client -> IRS : /ess/bpn/investigation/orders
note left
    {
      "bomLifecycle": "asPlanned","batchSize": 20,
        "callbackUrl": "https://hostname.com/callback?orderId={orderId}&batchId={batchId}",
      ...
      "incidentBPNSs": [
        "BPNL666666666666","BPNL666666666667"
      ],
      "keys": [
        {
          "bpn": "BPNL0123456789XX",
          "globalAssetId": "urn:uuid:6c311d29-5753-46d4-b32c-19b918ea93b0"
        },
        {
          "bpn": "BPNL9876543210XX",
          "globalAssetId": "urn:uuid:6c311d29-5753-46d4-b32c-19b918ea9333"
        }
      ],
      "timeout": 43200
    }
end note
IRS --> IRS : initale order processing
    ref over EDC, EDCTier1, SubmodelServerTier1, dDTRTier1, EDCConsumerTier1, DiscoveryFinder, EDCDiscoveryService
        asyn processing of ess process for incidentBPNSs
        and tuples of globalAssetid and BPN
    end ref
IRS --> IRS : register callback
IRS <-- IRS : 201 success
IRS <-- IRS : orderId {"6c311d29-5753-46d4-b32c-19b918ea93b0"}
Client <-- IRS : 201 orderId {"6c311d29-5753-46d4-b32c-19b918ea93b0"}

opt batch complete
    Client <-- IRS : Callback order with orderId completed
end opt
    Client --> IRS : /irs/orders/{orderId}/batches/{batchId}
    Client <-- IRS : BatchShell with jobs

@enduml
