@startuml

skinparam monochrome true
skinparam shadowing false

hide empty description

state INITIAL {
    state "MultiTransferJob registered"

}
state IN_PROGRESS {
    state "MultiTransferJob running"

}
state TRANSFERS_FINISHED {
    state "TransferProcess completed"
}
state ACK_Required <<choice>>

state ACKNOWLEDGE {
    state "MultiTransferJob complete"
}
state ACK_POSITIVE <<choice>>

state COMPLETED {
    state "Job acknowledge succeed"
}

[*] --> UNSAVED
UNSAVED -> INITIAL : register job
INITIAL -> IN_PROGRESS : start job
IN_PROGRESS -> TRANSFERS_FINISHED : execute TransferProcesses
TRANSFERS_FINISHED --> ACK_Required
ACK_Required --> COMPLETED : [No]
ACK_Required --> ACKNOWLEDGE : [Yes]
ACKNOWLEDGE --> ACK_POSITIVE
ACK_POSITIVE -> COMPLETED : [Yes]
ACK_POSITIVE --> ERROR : [No]
COMPLETED : complete job execution
COMPLETED --> [*]
UNSAVED --> ERROR
INITIAL --> ERROR
IN_PROGRESS --> ERROR
TRANSFERS_FINISHED --> ERROR
ERROR -> [*]

@enduml
