@startuml
skinparam monochrome true
skinparam shadowing false


|IRS 1|
start
:Start search **(globalAssetId)**;
note
    IRS API is requested
    POST http://Tier1_333/irs/jobs
    mode: aggregation
    aspects:ESRCertificatesStatistics
    globalAssetID: 3333
    bomLifecycle: asBuilt
end note
:Get AAS **(globalAssetId))**;
note
    Request AAS Shell in
    DT Registry for globalAssetId
end note
|#AntiqueWhite|DT Registry|
:Lookup AAS **(globalAssetId))**;
|IRS 1|
:Get Childs via AssemblyPartRelationship;
note
    Extract endpoints for each
    Child (AssemblyPartRelationShip)
end note
:Get AAS shells for Children;

partition lookopCertificate {
:Get BPNL number of requestor and supplier;
note
    BPNL number of requestor AAS shell
    BPNL number of supplier AAS shell
end note
:SupplyON ISO14001 Certificate check
 for each child;
|SupplyOnAPI|
:Lookup ISO14001 Certificate;
|IRS 1|
:Add ISO14001 Certificate
to Jobs#submodels[];
if (!EsrCertificateStatistics.exists()) then
:createEsrCertificateStatistics;
endif
:Add ISO14001 Certificate state
 to EsrCertificateStatistics;
note
    EsrCertificateStatistics attributes are incremented
    according to returned status
end note
}
partition lookopEsrCertificateStatisitcsPayload {
if(hasEsrCertificateStatistics?) then (yes)
:Call EsrCertificateStatistics endpoint;
note
    in case an endpoint is available it points to the
    IRS instance on next level
end note
|IRS 2|
:Start Search (globalAssetId);
:Get AAS (globalAssetId));
note
 Similar procedure like call on IRS1
end note
|#AntiqueWhite|DT Registry|
:Lookup AAS;
|IRS 2|
:Get Childs via AssemblyPartRelationship;
: ....;
note
    same procedure like IRS1
end note
: ....;
note
    same procedure like IRS1
end note
:Receive JobResponse with
EsrCertificateStatistics;
:Aggregate EsrCertificateStatistics into JobResponse;
:Filter ISO14001 Payload from JobResponse;

endif;
|IRS 1|
:Receive JobResponse with
EsrCertificateStatistics;
:Aggregate EsrCertificateStatistics into JobResponse;
:Filter ISO14001 Payload from JobResponse;
}
stop
@enduml