{
 "title": "IRS-Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Job Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_created_total[100y])"
    }
   ]
  },
  {
   "title": "Total Completed Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jobs_jobstate_sucessful_total[100y])"
    }
   ]
  },
  {
   "title": "Total Running Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"running\"}"
    }
   ]
  },
  {
   "title": "Job Exception",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"exception\"}"
    }
   ]
  },
  {
   "title": "Cancelled Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstate_cancelled_total{jobstate=\"cancelled\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"failed\"}"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "jobs_snapshot_success", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_running", "legendFormat": "{{label_name}}" },
    { "expr": "jobs_snapshot_cancelled", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job in JobStore",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstore{jobstate=\"jobs_in_store\"}"
    }
   ]
  },
  {
   "title": "Process time (Milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "job_execution_time{jobtimer=\"getjobbystate\"}"
    },
    {
     "expr": "job_execution_time{jobtimer=\"registerjob\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Stat",
   "type": "stat",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_snapshot_success", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_running", "legendFormat": "{{label_name}}" },
    { "expr": "jobs_snapshot_cancelled", "legendFormat": "__auto" },
    { "expr": "jobs_snapshot_failed", "legendFormat": "__auto" }
   ]
  }
 ]
}