{
 "title": "IRS-Jobs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Job Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_created_total{}" }
   ]
  },
  {
   "title": "Completed Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstate_sucessful_total{}"
    }
   ]
  },
  {
   "title": "Job Successful",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstate_sucessful_total{}"
    }
   ]
  },
  {
   "title": "Job Exception",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"exception\"}"
    }
   ]
  },
  {
   "title": "Cancelled Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstate_cancelled_total{jobstate=\"cancelled\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"failed\"}"
    }
   ]
  },
  {
   "title": "Running Job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{jobstate=\"running\"}"
    }
   ]
  },
  {
   "title": "Job in JobStore",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jobs_jobstore{jobstate=\"jobs_in_store\"}"
    }
   ]
  },
  {
   "title": "Create Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "jobs_created_total", "legendFormat": "__auto" }
   ]
  }
 ]
}