{
 "title": "IRS-API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Successful Request to /irs/job",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/irs/jobs\", status=\"200\"}[100y]))"
    }
   ]
  },
  {
   "title": "Total Post Request to application",
   "type": "stat",
   "description": "Total Request",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{method=\"POST\", outcome=\"SUCCESS\"}[100y]))"
    }
   ]
  },
  {
   "title": "Retry Request",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_retries_total{}[100y]))"
    },
    {
     "expr": "sum(increase(http_requests_retries_total{}[24h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(http_requests_retries_total{}[1h]))"
    },
    {
     "expr": "sum(increase(http_requests_retries_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Total Request to /irs/jobs",
   "type": "bargauge",
   "description": "Total Request to /irs/jobs",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/irs/jobs\"}[100y]))"
    }
   ]
  },
  {
   "title": "Total Error Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{outcome=\"CLIENT_ERROR\", uri=\"/irs/jobs\"}[100y]))"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{outcome=\"SERVER_ERROR\", uri=\"/irs/jobs\"}[100y]))"
    }
   ]
  },
  {
   "title": "Number of Timeout",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_requests_timeouts_total{}[100y])"
    }
   ]
  },
  {
   "title": "Exception",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{outcome!=\"SUCCESS\", uri=\"/irs/jobs\"}[24h]))"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{outcome!=\"SUCCESS\", uri=\"/irs/jobs\"}[1h]))"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_sum{outcome!=\"SUCCESS\", uri=\"/irs/jobs\"}[1m]))"
    }
   ]
  }
 ]
}