TF_VAR_environment="dev"
TF_VAR_resource_group_name="catenax-dev001-rg"
TF_VAR_image_registry="catenaxdev001acr.azurecr.io"
TF_VAR_ingress_host="catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com"
TF_VAR_ingress_class_name="nginx"
TF_VAR_aks_cluster_name="catenax-dev001-aks-services"
