TF_VAR_environment="int"
TF_VAR_resource_group_name="catenax-int-rg"
TF_VAR_image_registry="catenaxintacr.azurecr.io"
TF_VAR_ingress_host="catenaxintakssrv.germanywestcentral.cloudapp.azure.com"
TF_VAR_ingress_class_name="service"
TF_VAR_aks_cluster_name="catenax-int-aks-services"
