@startuml 
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20

[**IRS**] <<System>> as IRS

[**EDC**] <<Component>> as EDC



node "Digital Twin Registry" {
    [**AAS Registry**] <<Component>> as AASR
}
node "Group of Submodel Endpoints" {
  [**Submodel-Server**] <<Component>> as SN
}
node "Central Services" {
    node "IAM" {
        [**OAuth2**] <<Component>> as OAuth2
    }
    [**Discovery Service**] <<Central Service>> as DS
    interface "Discovery API" as DAPI

}
actor Consumer


interface "IRS API" as IAPI
interface "EDC API" as IEDC
interface "Registry API" as IRAPI
interface "Submodel API" as ISubModelAPI

Consumer -( IAPI
IAPI - IRS
IRS --( DAPI
IRS -- OAuth2
IRS -( IEDC

DS -- OAuth2
DS - DAPI

IEDC - EDC
EDC --( ISubModelAPI
ISubModelAPI - SN
EDC -( IRAPI
IRAPI - AASR

@enduml