= Technical context

[plantuml, target=integrated-overview, format=svg]
....
@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20

[**IRS**] <<System>> as IRS

[**AAS Wrapper**] <<Component>> as AASW



node "Digital Twin Registry" {
    [**AAS Registry**] <<Component>> as AASR
}
node "Group of Submodel Endpoints" {
  [**Submodel-Server**] <<Component>> as SN
}
node "IAM" {
    [**Keycloak**] <<Component>> as KIAM
}
actor Consumer

interface "IRS API" as IAPI
interface "AASWrapper API" as IAASW
interface "Registry API" as IRAPI
interface "Submodel API" as ISubModelAPI
interface "OIDC" as IAMAPI

Consumer -( IAPI
IAPI - IRS
IAASW - AASW
IRS -( IAASW
ISubModelAPI - SN
AASW -( ISubModelAPI
IRS --( IRAPI
IRAPI -- AASR
IRS --down( IAMAPI
AASR --( IAMAPI
KIAM -- IAMAPI
@enduml
....

== Component overview

=== IRS-API
We provide a REST API that can be consumed by any system registered in the Catena-X Keycloak, e.g. the Dismantler Dashboard. The development of such a consumer service is not part of the IRS application. Each system that acts as a client to the Restful application IRS can be used instead, if it supports any REST call of the designed REST endpoints in the REST Controller of the IRS application. For communication, the transport protocol HTTP(S) should be established.

In order to consume the Restful application IRS, the security aspect should be taken in consideration. IRS is a Spring Boot based application and is secured with the OpenID connector provider Keycloak and the OAuth2. This means for the consumers (users) that they need to authenticate themselves in order to be authorized to get access to the IRS. They generate a bearer token that they get from Keycloak and attach it to the HTTP header parameter Authorization. Certainly, both a consumer and the IRS should use the same configured Keycloak Realm.

=== Registry API
The IRS acts as a consumer of the component Asset Administration Shell Registry. The IRS contains a Restful client (REST template) that build a REST call to the mentioned Digital Twin Registry API based on its known URL (the AAS registry URL is configured in the IRS Restful API). The request contains the given "globalAssetId" by the consumer. Like described in the above section, the security aspect is required in order to achieve a REST call against the AAS Registry. As a response, the IRS gets the corresponding asset administration shell descriptor. The last one contains a list of submodel descriptors which can be filtered by the aspect type entered by the consumer. An aspect type like AssemblyPartRelationship, SerialPartTypization etc. And as mentioned above, the transport protocol HTTP(S) is used for the REST call communication.

=== AAS Wrapper API
The integrated Restful client named Submodel Client in the IRS is responsible for creating Restful requests to the component AAS Wrapper. The IRS application builds from the retrieved AAS Descriptor (see previous section) the corresponding Submodel endpoint URLs and sends via the submodel REST client requests to the AAS Wrapper API. The last one responds with the corresponding Submodel data.