= Quality requirements

The quality scenarios in this section depict the fundamental quality goals as well as other required quality properties. They allow the evaluation of decision alternatives.

- *Quality attribute*: A characteristic of software, or a generic term applying to quality factors, quality subfactors, or metric values.
- *Quality factor*: A management-oriented attribute of software that contributes to its quality.
- *Quality subfactor*: A decomposition of a quality factor or quality subfactor to its technical components.
- *Metric value*: A metric output or an element that is from the range of a metric.
- *Software quality metric*: A function whose inputs are software data and whose output is a single numerical value that can be interpreted as the degree to which software possesses a given attribute that affects its quality.

*Source*: IEEE standard 1061 “Standard for a Software Quality Metrics Methodology”

== List of requirements

=== C-1: Backward-compatibility of IRS application

*Scenario*: (IRS network of network)

Master IRS (IRS witch initiates the request) has a higher version than those IRS in the network.

*IRS Instances*:

IRS application MUST interact and operate with former versions (compatibility is ensured for application inside one MAJOR version) of IRS.

*Out of scope*:

Backward-compatibility between different major versions of IRS.

*Considerations*:

*Cluster*: Network of network approach. Multiple IRS instances communication over the network of different providers and partners. Prerequisite for a functioning IRS network cluster would be IRS installed with an equal major version to ensure api compatibility.

That IRS with exactly the same version are installed over the complete network at the same time is maybe not realistic. Because of this reason multiple version should operate which each other.

- Strict release management: Avoid any incompatible API changes inside minor or patch version
- Testing: Backward Compatibility Testing: test compatibility between all minor and patch versions inside a major version.

JobResponse could provide different results if there is a change in JobResponse schema.

=== C-2: Backward-compatibility of JobResponse schema inside IRS

*Schema JobResponse*:

- JobResponse document is versioned.
- JobResponse document is released.
- JobResponse document has a semantic version.

*Questions*:

Dealing with different JobRespones version. (What if IRS is updated and consumer app has not implemented the actual version of JobResponse.

IRS API provides JobResponse in requested version. API parameter requesting JobResponse response in a given version. /irs/jobs {jobRespponseVers=1.1.2} Different versions of the JobResponse document could be requested over the API.  Version is a parameter which could be requested over API. The reponse will be transformed to

API passes back a JobResponse with a given version. API supports a given version range of JobResponse.


*HATEOS*

HATEOAS requires a different approach. JobResponse has no unique version.
- (A) Each subdocument could have a seperate version.
- (B) Master JobResponse document and sub documents (submodel, thumbstones) are always released under the same version.

=== C-3: Backward-compatibility of AAS shells processing inside IRS

*AAS Shell (DT registry)*

* Single IRS instance could handle AAS shells in different version. AAS shells requested from the DT registry could be processed within a given version range. AAS3.0.0 - AAS.4.1.0
* Multiple IRS instances working together in a IRS network approach could process AAS documents in a given version range.
* Work with different AAS shell versions.
** Which is the leading version?
** Do we provide different versions?

=== C-4: Backward-compatibility of processed AspectModels inside IRS

*AspectModels*

* Any released AspectModels version within a given version range could be processed by IRS.
* Only between major releases or any version from 1.0.0 up.
* Validation on different aspect models

=== C-5: Forward-compatibility of IRS application

*IRS Instances*:

*Scenario: (IRS network of network)*

* Master IRS (IRS witch initiates the request) has a lower version than those IRS in the network.

* IRS Instances could interact and operate with newer/further version of IRS. (Until a certain grade? Major release or more years? )

*Schema:*

* Design is very flexible to take certain changes under account. Serialization of JSON is not made. If some core information has not changed, the IRS is still able to process documents.
* IRS defines the core constraints which must not change in aspect model structure and those which could change

=== C-6: Semantic Versioning approach for application and provided artifact

IRS uses semantic versioning. Following https://semver.org/.

Version number MAJOR.MINOR.PATCH

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards compatible manner, and
* PATCH version when you make backwards compatible bug fixes.


Candidates:

* JobResponse Schema Version
* IRS Application Version
* API versioning
** Concept for Backward-compatibility (API contracts)
** Develop a API Versioning Strategy
*** e.g. Versioning through api path /irs/v1.5/../

=== T-1: Monitoring of application collecting KPIs and metrics for resource allocation and core processing

* IRS provides a Grafana Monitoring Dashboard which covers the core metrics for Ressource monitoring, application performance, internal job processing metrics and errors and exceptions occurred on external system calls.
* Collection of extended metrics and the creation of new Dashboards could be extended by developers.

Collection and analysis of data to detect, report (alerting) and analyse disruptions in advance or when they occur. To clarify if the application running within the defined operating resources and parameters.

* Grafana Dashboard, providing dashboard with aggregated and detailed information for the following categories:
** Resources Monitoring
*** CPU
*** Memory
*** Threads
** Job Details Monitoring
*** Metrics for job processing details
*** Jobs with job states
*** Error and failures in processing
** IRS Consumer API
*** Requests
*** Roundtrip time
*** Latency
*** ...
** IRS AAS API
*** Request details
*** Latency
*** Details to retry information
* Usage of Prometheus monitoring solution, collecting application and resource metrics and provides them for different visualization application like the most common is Grafana.

=== M-1: API Contracts and Design

Well-defined interfaces and API contracts

(question) Usage of API Linter (https://linter.aip.dev/)

(question) Usage of // Spectral Ruleset for API Design Guidelines

(question) https://stoplight.io/open-source/spectral

Spectral Ruleset for API Design Guidelines
https://github.com/doubleSlashde/API-Design-Guidelines

https://doubleslashde.github.io/API-Design-Guidelines/REST_API_Guidelines.pdf

The latest version of API Guidelines from doubleSlash Net-Business GmbH are available in the following formats.
Johannes Zahn Benefit would be, to have clear and documented API Design Guideline which are checked using an API Linter. This will take additional effort but will cause a clear and reasonable api documentation based on clear rules.