IRS Iterative is the main IRS mode for retrieving data chains throughout the Catena-X network. The core functionality can be summed up in three steps:

1. Start the process with a provided globalAssetId and BPN combination, and required submodels to request.
2. Retrieve the EDC endpoint for the BPN, search the catalog for the Digital Twin Registry contract Offer and search the DTR for the provided BPN.
3. Retrieve the relationship submodel for the requested lifecycle and direction and repeat step 1 with the globalAssetIds and BPNs from the relationship submodel linked data until the desired depth is reached or no more relationships could be found.

[plantuml, target=overall, format=svg]
....
include::../../../../uml-diagrams/runtime-view/api-call-asynchrous-sequence.puml[]
....

== Submodel

This section describes how the IRS fetches submodel payload.

[plantuml, target=submodel-processing, format=svg]
....
include::../../../../uml-diagrams/runtime-view/aas-shell-and submodel-processing.puml[]
....

== Job orchestration flow

This section describes the job orchestration in IRS.

[plantuml, target=job-orchestration, format=svg]
....
include::../../../../uml-diagrams/runtime-view/job-orchestration-sequence.puml[]
....

== Policy store flow

This section describes the policy store in IRS.

[plantuml, target=policy-store, format=svg]
....
include::../../../../uml-diagrams/policy-store/policy-storage-processing.puml[]
....

== Policy check procedure

This section describes the way IRS is validating policies found in assets.

[plantuml, target=policy-check, format=svg]
....
include::../../../../uml-diagrams/policy-store/policy-validation-processing.puml[]
....
