---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-data-plane.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    web.http.default.port={{ .Values.edc.endpoints.default.port }}
    web.http.default.path={{ .Values.edc.endpoints.default.path }}
    web.http.public.port={{ .Values.edc.endpoints.public.port }}
    web.http.public.path={{ .Values.edc.endpoints.public.path }}
    web.http.control.port={{ .Values.edc.endpoints.control.port }}
    web.http.control.path={{ .Values.edc.endpoints.control.path }}
    edc.api.auth.key={{ .Values.edc.api.auth.key }}
    edc.dataplane.token.validation.endpoint={{ .Values.edc.dataplane.token.validation.endpoint }}
    edc.oauth.client.id={{ .Values.edc.oauth.client.id }}
    edc.oauth.private.key.alias={{ .Values.edc.oauth.private.key.alias }}
    edc.oauth.provider.jwks.url={{ .Values.edc.oauth.provider.jwks.url}}
    edc.oauth.certificate.alias={{ .Values.edc.oauth.public.key.alias }}
    edc.oauth.token.url={{ .Values.edc.oauth.token.url }}
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.enabled=false
    edc.vault.hashicorp.url={{ .Values.edc.vault.hashicorp.url }}
    edc.vault.hashicorp.token={{ .Values.edc.vault.hashicorp.token }}
    edc.vault.hashicorp.api.secret.path={{ .Values.edc.vault.hashicorp.api.secret.path }}

  opentelemetry.properties: |-
    {{- .Values.opentelemetry.properties | nindent 4 }}

  logging.properties: |-
    {{- .Values.logging.properties | nindent 4 }}