apiVersion: v1
kind: Secret
metadata:
  name: prs-secrets
type: Opaque
data:
  postgresql_username: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql_password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  eventhubs_send: {{ printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=%q password=%q;" "$ConnectionString" .Values.eventHubs.sendConnectionString | b64enc | quote }}
  eventhubs_listen: {{ printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=%q password=%q;" "$ConnectionString" .Values.eventHubs.receiveConnectionString | b64enc | quote }}
