[#_configuration]
= Configuration
:icons: font

Take the following template and adjust the configuration parameters (<placeholders> mark the relevant spots).
You can define the URLs as well as most of the secrets yourself.

The Keycloak, DAPS and Vault configuration / secrets depend on your setup and might need to be provided externally.

== Helm configuration (values.yaml)

[source,yaml]
----
irs:
  #####################
  # IRS Configuration #
  #####################
  irsUrl: "https://<irs-url>"
  global:
    enablePrometheus: true #<1>
    enableGrafana: true #<1>
  ingress:
    hosts:
      - host: "<irs-url>"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "<irs-url>"
        secretName: tls-secret
  digitalTwinRegistry:
    url: https://<digital-twin-registry-url>
  minioUser: <minio-username>
  minioPassword: <minio-password>
  keycloak:
    oauth2:
      clientId: <keycloak-client-id>
      clientSecret: <keycloak-client-secret>
      clientTokenUri: <keycloak-token-uri>
      jwkSetUri: <keycloak-jwkset-uri>
  aasWrapper:
    username: <aas-wrapper-username>
    password: <aas-wrapper-password>

  #######################
  # Minio Configuration #
  #######################
  irs-minio:
    minioUser: <minio-username>
    minioPassword: <minio-password>

  ############################
  # AASWrapper Configuration #
  ############################
  irs-aaswrapper:
    edc:
      api:
        auth:
          key: "<edc-api-key>"

  #########################
  # Grafana Configuration #
  #########################
  irs-grafana: #<2>
    ingress:
      hosts:
        - host: "<grafana-url>"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "<grafana-url>"
          secretName: tls-secret

    username: <grafana-username>
    password: <grafana-password>

  ##############################
  # EDC Postgres Configuration #
  ##############################
  postgresql:
    auth:
      postgresPassword: <postgres-admin-password>
      password: <postgres-password>

  ##################################
  # EDC Controlplane Configuration #
  ##################################
  edc-controlplane:
    ingresses:
      - enabled: true
        hostname: "<controlplane-url>"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - ids
          - data
        className: ""
        tls:
          - hosts:
              - "<controlplane-url>"
            secretName: tls-secret
        certManager:
          issuer: ""
          clusterIssuer: ""

    edc:
      postgresql:
        password: <postgres-password>
      transfer:
        proxy:
          token:
            verifier:
              publickey:
                alias: <daps-certificate-name>
            signer:
              privatekey:
                alias: <daps-privatekey-name>
      api:
        auth:
          key: "<edc-api-key>"
      controlplane:
        url: "https://<controlplane-url>"
      dataplane:
        url: "https://<dataplane-url>"
    configuration:
      properties: |-
        edc.oauth.client.id=<daps-client-id>
        edc.oauth.private.key.alias=<daps-privatekey-name>
        edc.oauth.provider.jwks.url=<daps-jwks-url>
        edc.oauth.public.key.alias=<daps-certificate-name>
        edc.oauth.token.url=<daps-token-url>
        edc.vault.hashicorp.url=<vault-url>
        edc.vault.hashicorp.token=<vault-token>
        edc.vault.hashicorp.api.secret.path=<vault-secret-store-path>
        edc.data.encryption.keys.alias=<daps-privatekey-name>
        edc.data.encryption.algorithm=NONE

  ###############################
  # EDC Dataplane Configuration #
  ###############################
  edc-dataplane:
    edc:
      api:
        auth:
          key: "<edc-api-key>"
    ## Ingress declaration to expose the network service.
    ingresses:
      ## Public / Internet facing Ingress
      - enabled: true
        # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
        hostname: "<dataplane-url>"
        # -- Additional ingress annotations to add
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        # -- EDC endpoints exposed by this ingress resource
        endpoints:
          - public
        # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
        className: "nginx"
        # -- Enables TLS on the ingress resource
        tls:
          - hosts:
              - "<dataplane-url>"
            # Default secret for certificate creation already provided to your namespace
            secretName: tls-secret
        ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
        certManager:
          # -- If preset enables certificate generation via cert-manager namespace scoped issuer
          issuer: ""
          # -- If preset enables certificate generation via cert-manager cluster-wide issuer
          clusterIssuer: ""

    configuration:
      properties: |-
        edc.oauth.client.id=<daps-client-id>
        edc.oauth.private.key.alias=<daps-privatekey-name>
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=<daps-jwks-url>
        edc.oauth.public.key.alias=<daps-certificate-name>
        edc.oauth.token.url=<daps-token-url>
        edc.vault.hashicorp.url=<vault-url>
        edc.vault.hashicorp.token=<vault-token>
        edc.vault.hashicorp.api.secret.path=<vault-secret-store-path>

----
<1> Use this to enable or disable the monitoring components
<2> This block can be removed if Grafana is disabled

== Secrets
This is a list of all secrets used in the deployment.

|===
|Name | Description

|<postgres-admin-password>
|Database password for the *postgres* user

|<postgres-password>
|Database password for the application user (default username: *edc*)

|<keycloak-client-id>
|Client ID for Keycloak. Request this from your Keycloak operator.

|<keycloak-client-secret>
|Client secret for Keycloak. Request this from your Keycloak operator.

|<minio-username>
|Login username for Minio

|<minio-password>
|Login password for Minio

|<edc-api-key>
|A self defined API key for the EDC API

|<vault-token>
|The access token for the HashiCorp Vault API

|<grafana-username>
|Login username for Grafana

|<grafana-password>
|Login password for Grafana

|<aas-wrapper-username>
|Basic authentication of the AAS Wrapper API. You can leave this empty.

|<aas-wrapper-password>
|Basic authentication of the AAS Wrapper API. You can leave this empty.
