[#_configuration]
= Configuration

Because IRS relies on multiple components, the following configuration parameters of values.yaml need to be adjusted:
(<app-name> refers to the name the application is given in ArgoCD)

== Secrets
This is a list of all secrets used in the deployment.

|===
|Name | Description | Required

|secret/controlplane/databaseUsername
|Database user for the EDC controlplane
|yes

|secret/controlplane/databasePassword
|Database password for the EDC controlplane
|yes

|secret/keycloak/oauth2/clientId
|Client credentials for Keycloak
|yes

|secret/keycloak/oauth2/clientSecret
|Client credentials for Keycloak
|yes

|secret/keycloak/oauth2/jwkSetUri
|URI of the Keycloak JWK endpoint
|yes

|secret/keycloak/oauth2/tokenUri
|URI of the Keycloak Token endpoint
|yes

|secret/minio/minioUser
|Login credentials for Minio
|yes

|secret/minio/minioPassword
|Login credentials for Minio
|yes

|secret/grafana/username
|Login credentials for Grafana
|no

|secret/grafana/password
|Login credentials for Grafana
|no

|secret/aasWrapper/username
|Basic authentication of the AAS Wrapper API
|no

|secret/aasWrapper/password
|Basic authentication of the AAS Wrapper API
|no

|===

== Integrated (minimal) configuration

== Standalone configuration

[source,yaml]
----
ingress:
  hosts:
    - host: "<public-irs-hostname>"
  tls:
    - hosts:
        - "<public-irs-hostname>"

keycloak:
  oauth2:
    clientId: <path:path/to/hashicorp/vault/oauth2#clientId>
    clientSecret: <path:path/to/hashicorp/vault/oauth2#clientSecret>
    clientTokenUri: <path:path/to/hashicorp/vault/oauth2#tokenUri>
    jwkSetUri: <path:path/to/hashicorp/vault/oauth2#jwkSetUri>

aasWrapper:
  host: http://<app-name>-irs-aaswrapper:9191/api/service
  username: <path:path/to/hashicorp/vault/wrapper#username> # currently not used
  password: <path:path/to/hashicorp/vault/wrapper#password> # currently not used

minio:
  url: http://<app-name>-irs-minio:9000

rootUser: <path:path/to/hashicorp/vault/minio#minioUser>
rootPassword: <path:path/to/hashicorp/vault/minio#minioPassword>

digitalTwinRegistry:
  url: <digital-twin-registry-url>

global:
  enablePrometheus: false # set to true to enable prometheus
  enableGrafana: false    # set to true to enable grafana

irs-grafana:
  username: <path:path/to/hashicorp/vault/grafana#username>
  password: <path:path/to/hashicorp/vault/grafana#password>

  ingress:
    hosts:
      - host: "<public-grafana-hostname>"
    tls:
      - hosts:
          - "<public-grafana-hostname>"
  config:
    datasources:
        url: http://<app-name>-irs-prometheus:9090

  oauthClientId: <path:path/to/hashicorp/vault/grafana#oauthClientId> # currently not used)
  oauthClientSecret: <path:path/to/hashicorp/vault/grafana#oauthClientSecret> # currently not used

  configEnvs:
    - name: GF_SERVER_ROOT_URL
      value: 'https://<public-grafana-hostname>'

irs-prometheus:
  config:
    scrape_configs:
      - job_name: 'spring-actuator'
        static_configs:
          - targets: [ '<app-name>:4004' ]
      - job_name: 'minio-actuator'
        static_configs:
          - targets: [ '<app-name>-irs-minio:9000' ]

irs-minio:
  rootUser: <path:path/to/hashicorp/vault/minio#minioUser> # the same as above rootUser
  rootPassword: <path:path/to/hashicorp/vault/minio#minioPassword> # the same as above rootPassword

edc-controlplane:
  ingresses:
      hostname: "<public-edc-controlplane-hostname>"
      tls:
        - hosts:
            - "<public-edc-controlplane-hostname>"
  configuration:
    properties: |-
      ids.webhook.address=https://<public-edc-controlplane-hostname>
      edc.ids.endpoint=https://<public-edc-controlplane-hostname>/api/v1/ids
      edc.ids.endpoint.audience=https://<public-edc-controlplane-hostname>/api/v1/ids/data
      edc.receiver.http.endpoint=http://<app-name>-irs-aaswrapper:9192/callback/endpoint-data-reference

      edc.transfer.proxy.endpoint=https://<public-edc-dataplane-hostname>/api/public
      edc.dataplane.selector.consumer.properties={ "publicApiUrl": "https://<public-edc-dataplane-hostname>/api/public" }

      edc.oauth.client.id=<DAPS-client-ID>
      edc.oauth.private.key.alias=<hashicorpvault-daps-key-name>
      edc.oauth.public.key.alias=<hashicorpvault-daps-cert-name>

      edc.vault.hashicorp.token=<path:path/to/hashicorp/vault/vaultToken>
      edc.vault.hashicorp.api.secret.path=/v1/<hashicorp-namespace>

      edc.data.encryption.keys.alias=<hashicorpvault-daps-key-name>

      edc.datasource.asset.url=jdbc:postgresql://<app-name>-postgresql-hl:5432/edc
      edc.datasource.asset.user=<path:traceability-irs/data/int/controlplane#databaseuser>
      edc.datasource.asset.password=<path:traceability-irs/data/int/controlplane#databasepassword>

      edc.datasource.contractdefinition.url=jdbc:postgresql://<app-name>-postgresql-hl:5432/edc
      edc.datasource.contractdefinition.user=<path:path/to/hashicorp/vault/controlplane#databaseuser>
      edc.datasource.contractdefinition.password=<path:path/to/hashicorp/vault/controlplane#databasepassword>

      edc.datasource.contractnegotiation.url=jdbc:postgresql://<app-name>-postgresql-hl:5432/edc
      edc.datasource.contractnegotiation.user=<path:path/to/hashicorp/vault/controlplane#databaseuser>
      edc.datasource.contractnegotiation.password=<path:path/to/hashicorp/vault/controlplane#databasepassword>

      edc.datasource.policy.url=jdbc:postgresql://<app-name>-postgresql-hl:5432/edc
      edc.datasource.policy.user=<path:path/to/hashicorp/vault/controlplane#databaseuser>
      edc.datasource.policy.password=<path:path/to/hashicorp/vault/controlplane#databasepassword>

      edc.datasource.transferprocess.url=jdbc:postgresql://<app-name>-postgresql-hl:5432/edc
      edc.datasource.transferprocess.user=<path:path/to/hashicorp/vault/controlplane#databaseuser>
      edc.datasource.transferprocess.password=<path:path/to/hashicorp/vault/controlplane#databasepassword>

edc-dataplane:
  ingresses:
    - enabled: true
      hostname: "<public-edc-dataplane-hostname>"
      tls:
        - hosts:
            - "<public-edc-dataplane-hostname>"
  configuration:
    properties: |-
      edc.receiver.http.endpoint=http://<app-name>-irs-aaswrapper:9192/callback

      edc.oauth.client.id=<DAPS-client-ID>
      edc.oauth.private.key.alias=<hashicorpvault-daps-key-name>
      edc.oauth.public.key.alias=<hashicorpvault-daps-cert-name>

      edc.vault.hashicorp.token=<path:path/to/hashicorp/vault/vaultToken>
      edc.vault.hashicorp.api.secret.path=/v1/<hashicorp-namespace>

postgresql:
  auth:
    postgresPassword: <path:path/to/hashicorp/vault/controlplane#databasepassword>
    username: <path:path/to/hashicorp/vault/controlplane#databaseuser>
    password: <path:path/to/hashicorp/vault/controlplane#databasepassword>
----