[#_configuration]
= Configuration
:icons: font
:icon-set: fas

Take the following template and adjust the configuration parameters (<placeholders> mark the relevant spots).
You can define the URLs as well as most of the secrets yourself.

The OAuth2, MIW and Vault configuration / secrets depend on your setup and might need to be provided externally.

include::irs-spring-config.adoc[leveloffset=+1]

== Helm configuration IRS (values.yaml)

[source,yaml]
----
include::../../../../charts/irs-helm/values.yaml[lines=104..287]
----

<1> Use this to enable or disable the monitoring components


=== Values explained
==== <irs-url>
The hostname where the IRS will be made available.

=== <ingress>
To expose the IRS service, you need to add an ingress for the default port 8080.
You can do this by adding this to ingress:

[source,yaml]
----
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: "public.irs.hostname"
      paths:
        - path: /
          pathType: Prefix
          port: 8080
  tls:
    - hosts:
      - "public.irs.hostname"
      secretName: tls-secret
----

==== <digital-twin-registry-url>
The URL of the Digital Twin Registry. The IRS uses this service to fetch AAS shells.

==== <discovery-finder-url>
The URL of the Discovery Finder. The IRS uses this service to discover EDC to a particular BPN.

==== <semantics-hub-url>
The URL of the SemanticsHub. The IRS uses this service to fetch aspect schemas for payload validation.

==== <bpdm-url>
The URL of the BPDM service. The IRS uses this service to fetch business partner information based on BPNs.

==== <oauth2-token-uri>
The URL of the OAuth2 token API. Used by the IRS for token creation to authenticate with other services.

==== <oauth2-jwkset-uri>
The URL of the OAuth2 JWK Set. Used by the IRS to validate tokens when the IRS API is called.

==== <grafana-url>
The hostname where Grafana will be made available.

==== <edc-controlplane-endpoint-data>
The EDC consumer controlplane endpoint URL for data management, including the protocol.
If left empty, this defaults to the internal endpoint of the controlplane provided by the irs-edc-consumer Helm chart.

==== <connectorEndpointService.cacheTTL>
When IRS calls EDC Discovery Service to fetch endpoints for BPNL's there is a cache mechanism between them, to improve performance.
This parameter define how long cache is maintained before it is cleared. Data is in ISO 8601.

== OAuth2 Configuration
OAuth2 protocol is used by IRS to protect the APIs and other resources. This means it is possible to configure and use any identity and access management tool that provides OAuth 2.0 functionality.

=== Semantic Model Provisioning
The IRS can retrieve semantic models in two ways:

1. via the Semantic Hub, if you provide the URL
2. via local schema files

If you activate both features, IRS will first try to resolve the models via the Hub and use the
local models as a fallback.

If you want to use local schema files, you need to provide them directly in the `values.yaml` file. Use the param `semanticsHub.localModels` to specify a map of all the local schemas.
The *key* of each entry is the `Base64` encoded URN of the model. The *value* is the `Base64` encoded content of the schema file itself. The entries will then be mounted into the IRS container and used on demand. For reference, see the example comment in the default `values.yaml`.

=== Policy store configuration
The IRS is exposing REST API to store Policies definitions.
Storage details can be configured in `application.yml` file with below fields:

[source,yaml]
----
policystore:
  persistence:
    endpoint: "${MINIO_URL}" # S3 compatible API endpoint (e.g. Minio)
    accessKey: "${MINIO_ACCESS_KEY}" # S3 access key
    secretKey: "${MINIO_SECRET_KEY}" # S3 secret key
    bucketName: irs-policy-bucket # the name of the S3 bucket to be created / used by the policy store
    daysToLive: -1 # number of days to keep policies in the store, use -1 to disable cleanup
----

If no custom policies are registered via REST API, IRS will use the default one configured with `irs-edc-client.catalog.acceptedPolicies` property. IRS will only negotiate contracts for offers with policies found in Policy Store.

== Use existing EDC consumer
If you want to use an existing EDC as consumer, you need to add the management endpoint URL of this edc to `edc.controlplane.endpoint.data`.
You also have to add an ingress for the IRS EDC EDR Token callback endpoint (default port: 8181):

[source,yaml]
----
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: "public.irs.hostname"
      paths:
        - path: /
          pathType: Prefix
          port: 8080
        - path: /internal
          port: 8181
          pathType: Prefix
  tls:
    - hosts:
      - "public.irs.hostname"
      secretName: tls-secret
----

== EDC consumer configuration
If you want to provide your own EDC consumer, add the EDC Helm Chart as dependency to your Chart.yaml. The helm chart and documentation can be found here: https://github.com/eclipse-tractusx/tractusx-edc/tree/main/charts/tractusx-connector[tractusx-connector]

== Secrets
This is a list of all secrets used in the deployment.

WARNING: Keep the values for these settings safe and do not publish them!

=== <common-client-id>
Client ID for OAuth2 provider. Request this from your OAuth2 operator.

=== <common-client-secret>
Client secret for OAuth2 provider. Request this from your OAuth2 operator.

=== <minio-username>
Login username for Minio. To be defined by you.

=== <minio-password>
Login password for Minio. To be defined by you.

=== <edc-api-key>
An API key for the EDC API. To be defined by you.

=== <vault-token>
The access token for the HashiCorp Vault API.

=== <grafana-username>
Login username for Grafana. To be defined by you.

=== <grafana-password>
Login password for Grafana. To be defined by you.
