[#_configuration]
= Configuration
:icons: font
:icon-set: fas

Take the following template and adjust the configuration parameters (<placeholders> mark the relevant spots).
You can define the URLs as well as most of the secrets yourself.

The Keycloak, MIW and Vault configuration / secrets depend on your setup and might need to be provided externally.

*Note: IRS currently does not support any roles or rights for the API. As long as you provide a valid access token, you can use the IRS API to view and control all jobs on the IRS instance.*

include::irs-spring-config.adoc[leveloffset=+1]

== Helm configuration IRS (values.yaml)

[source,yaml]
----
include::../../../../charts/irs-helm/values.yaml[lines=104..287]
----

<1> Use this to enable or disable the monitoring components


=== Values explained
==== <irs-url>
The hostname where the IRS will be made available.

==== <digital-twin-registry-url>
The URL of the Digital Twin Registry. The IRS uses this service to fetch AAS shells.

==== <discovery-finder-url>
The URL of the Discovery Finder. The IRS uses this service to discover EDC to a particular BPN.

==== <semantics-hub-url>
The URL of the SemanticsHub. The IRS uses this service to fetch aspect schemas for payload validation.

==== <bpdm-url>
The URL of the BPDM service. The IRS uses this service to fetch business partner information based on BPNs.

==== <keycloak-token-uri>
The URL of the Keycloak token API. Used by the IRS for token creation to authenticate with other services.

==== <keycloak-jwkset-uri>
The URL of the Keycloak JWK Set. Used by the IRS to validate tokens when the IRS API is called.

==== <grafana-url>
The hostname where Grafana will be made available.

==== <edc-controlplane-endpoint-data>
The EDC consumer controlplane endpoint URL for data management, including the protocol.
If left empty, this defaults to the internal endpoint of the controlplane provided by the irs-edc-consumer Helm chart.

=== Semantic Model Provisioning
The IRS can retrieve semantic models in two ways:

1. via the Semantic Hub, if you provide the URL
2. via local schema files

If you activate both features, IRS will first try to resolve the models via the Hub and use the
local models as a fallback.

If you want to use local schema files, you need to provide them directly in the `values.yaml` file. Use the param `semanticsHub.localModels` to specify a map of all the local schemas.
The *key* of each entry is the `Base64` encoded URN of the model. The *value* is the `Base64` encoded content of the schema file itself. The entries will then be mounted into the IRS container and used on demand. For reference, see the example comment in the default `values.yaml`.


== EDC consumer configuration
If you want to provide your own EDC consumer, add the EDC Helm Chart as dependency to your Chart.yaml. The helm chart and documentation can be found here: https://github.com/eclipse-tractusx/tractusx-edc/tree/main/charts/tractusx-connector[tractusx-connector]

== Secrets
This is a list of all secrets used in the deployment.

WARNING: Keep the values for these settings safe and do not publish them!

=== <keycloak-client-id>
Client ID for Keycloak. Request this from your Keycloak operator.

=== <keycloak-client-secret>
Client secret for Keycloak. Request this from your Keycloak operator.

=== <minio-username>
Login username for Minio. To be defined by you.

=== <minio-password>
Login password for Minio. To be defined by you.

=== <edc-api-key>
An API key for the EDC API. To be defined by you.

=== <vault-token>
The access token for the HashiCorp Vault API.

=== <grafana-username>
Login username for Grafana. To be defined by you.

=== <grafana-password>
Login password for Grafana. To be defined by you.
