[#_configuration]
= Configuration
:icons: font
:icon-set: fas

Take the following template and adjust the configuration parameters (<placeholders> mark the relevant spots).
You can define the URLs as well as most of the secrets yourself.

The Keycloak, DAPS and Vault configuration / secrets depend on your setup and might need to be provided externally.

== Helm configuration (values.yaml)

[source,yaml]
----
global:
  enablePrometheus: true #<1>
  enableGrafana: true #<1>
irs-helm:
  #####################
  # IRS Configuration #
  #####################
  irsUrl: "https://<irs-url>"
  ingress:
    hosts:
      - host: "<irs-url>"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "<irs-url>"
        secretName: tls-secret
  digitalTwinRegistry:
    url: https://<digital-twin-registry-url>
  semanticsHub:
    url: https://<semantics-hub-url>
  bpdm:
    url: https://<bpdm-url>
  minioUser: <minio-username>
  minioPassword: <minio-password>
  keycloak:
    oauth2:
      clientId: <keycloak-client-id>
      clientSecret: <keycloak-client-secret>
      clientTokenUri: <keycloak-token-uri>
      jwkSetUri: <keycloak-jwkset-uri>
  aasWrapper:
    username: <aas-wrapper-username>
    password: <aas-wrapper-password>

  #######################
  # Minio Configuration #
  #######################
  irs-minio:
    minioUser: <minio-username>
    minioPassword: <minio-password>

  ############################
  # AASWrapper Configuration #
  ############################
  irs-aaswrapper:
    edc:
      api:
        auth:
          key: "<edc-api-key>"

  #########################
  # Grafana Configuration #
  #########################
  irs-grafana: #<2>
    ingress:
      hosts:
        - host: "<grafana-url>"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - "<grafana-url>"
          secretName: tls-secret

    username: <grafana-username>
    password: <grafana-password>

  ##############################
  # EDC Postgres Configuration #
  ##############################
  postgresql:
    auth:
      postgresPassword: <postgres-admin-password>
      password: <postgres-password>

  ##################################
  # EDC Controlplane Configuration #
  ##################################
  edc-controlplane:
    ingresses:
      - enabled: true
        hostname: "<controlplane-url>"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - ids
          - data
        className: ""
        tls:
          - hosts:
              - "<controlplane-url>"
            secretName: tls-secret
        certManager:
          issuer: ""
          clusterIssuer: ""

    edc:
      postgresql:
        password: <postgres-password>
      transfer:
        proxy:
          token:
            verifier:
              publickey:
                alias: <daps-certificate-name>
            signer:
              privatekey:
                alias: <daps-privatekey-name>
      api:
        auth:
          key: "<edc-api-key>"
      controlplane:
        url: "https://<controlplane-url>"
      dataplane:
        url: "https://<dataplane-url>"
    configuration:
      properties: |-
        edc.oauth.client.id=<daps-client-id>
        edc.oauth.private.key.alias=<daps-privatekey-name>
        edc.oauth.provider.jwks.url=<daps-jwks-url>
        edc.oauth.public.key.alias=<daps-certificate-name>
        edc.oauth.token.url=<daps-token-url>
        edc.vault.hashicorp.url=<vault-url>
        edc.vault.hashicorp.token=<vault-token>
        edc.vault.hashicorp.api.secret.path=<vault-secret-store-path>
        edc.data.encryption.keys.alias=<daps-privatekey-name>
        edc.data.encryption.algorithm=NONE

  ###############################
  # EDC Dataplane Configuration #
  ###############################
  edc-dataplane:
    edc:
      api:
        auth:
          key: "<edc-api-key>"
    ingresses:
      - enabled: true
        hostname: "<dataplane-url>"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          - hosts:
              - "<dataplane-url>"
            secretName: tls-secret
        certManager:
          issuer: ""
          clusterIssuer: ""

    configuration:
      properties: |-
        edc.oauth.client.id=<daps-client-id>
        edc.oauth.private.key.alias=<daps-privatekey-name>
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=<daps-jwks-url>
        edc.oauth.public.key.alias=<daps-certificate-name>
        edc.oauth.token.url=<daps-token-url>
        edc.vault.hashicorp.url=<vault-url>
        edc.vault.hashicorp.token=<vault-token>
        edc.vault.hashicorp.api.secret.path=<vault-secret-store-path>

----
<1> Use this to enable or disable the monitoring components
<2> This block can be removed if Grafana is disabled

== Values explained
=== <irs-url>
The hostname where the IRS will be made available.

=== <digital-twin-registry-url>
The URL of the Digital Twin Registry. The IRS uses this service to fetch AAS shells.

=== <semantics-hub-url>
The URL of the SemanticsHub. The IRS uses this service to fetch aspect schemas for payload validation.

=== <bpdm-url>
The URL of the BPDM service. The IRS uses this service to fetch business partner information based on BPNs.

=== <keycloak-token-uri>
The URL of the Keycloak token API. Used by the IRS for token creation to authenticate with other services.

=== <keycloak-jwkset-uri>
The URL of the Keycloak JWK Set. Used by the IRS to validate tokens when the IRS API is called.

=== <grafana-url>
The hostname where Grafana will be made available.

=== <controlplane-url>
The hostname where the EDC consumer controlplane will be made available.

=== <dataplane-url>
The hostname where the EDC consumer dataplane will be made available.


== DAPS configuration
EDC requires a DAPS instance to function correctly. For more information on this, please refer to the https://github.com/catenax-ng/product-DAPS[DAPS] or the https://github.com/catenax-ng/product-edc[EDC] documentation.

=== <vault-url>
The base URL of the Vault instance.
EDC requires a running instance of HashiCorp Vault to store the DAPS certificate and private key.

=== <vault-secret-store-path>
The path to the secret store in Vault where the DAPS certificate and key can be found.

_Example: /v1/team-name_

=== <daps-certificate-name>
The name of the DAPS certificate in the Vault.

_Example: irs-daps-certificate_

=== <daps-privatekey-name>
The name of the DAPS private key in the Vault.

_Example: irs-daps-private-key_

=== <daps-client-id>
The DAPS client ID.

=== <daps-jwks-url>
The URL of the DAPS JWK Set.

_Example: https://daps-hostname/.well-known/jwks.json_

=== <daps-token-url>
The URL of the DAPS token API.

_Example: https://daps-hostname/token_

== Secrets
This is a list of all secrets used in the deployment.

WARNING: Keep the values for these settings safe and do not publish them!

=== <postgres-admin-password>
Database password for the *postgres* user. To be defined by you.

=== <postgres-password>
Database password for the application user (default username: *edc*). To be defined by you.

=== <keycloak-client-id>
Client ID for Keycloak. Request this from your Keycloak operator.

=== <keycloak-client-secret>
Client secret for Keycloak. Request this from your Keycloak operator.

=== <minio-username>
Login username for Minio. To be defined by you.

=== <minio-password>
Login password for Minio. To be defined by you.

=== <edc-api-key>
An API key for the EDC API. To be defined by you.

=== <vault-token>
The access token for the HashiCorp Vault API.

=== <grafana-username>
Login username for Grafana. To be defined by you.

=== <grafana-password>
Login password for Grafana. To be defined by you.

=== <aas-wrapper-username>
Basic authentication of the AAS Wrapper API. You can leave this empty if no basic auth is configured for the AAS Wrapper.

=== <aas-wrapper-password>
Basic authentication of the AAS Wrapper API. You can leave this empty if no basic auth is configured for the AAS Wrapper.

