[#_configuration]
= Configuration
:icons: font
:icon-set: fas

Take the following template and adjust the configuration parameters (<placeholders> mark the relevant spots).
You can define the URLs as well as most of the secrets yourself.

The Keycloak, DAPS and Vault configuration / secrets depend on your setup and might need to be provided externally.

include::irs-spring-config.adoc[leveloffset=+1]

== Helm configuration IRS (values.yaml)

[source,yaml]
----
include::../../../../charts/irs/values.yaml[lines=83..-1]
----
<1> Use this to enable or disable the monitoring components

=== Values explained
==== <irs-url>
The hostname where the IRS will be made available.

==== <digital-twin-registry-url>
The URL of the Digital Twin Registry. The IRS uses this service to fetch AAS shells.

==== <semantics-hub-url>
The URL of the SemanticsHub. The IRS uses this service to fetch aspect schemas for payload validation.

==== <bpdm-url>
The URL of the BPDM service. The IRS uses this service to fetch business partner information based on BPNs.

==== <keycloak-token-uri>
The URL of the Keycloak token API. Used by the IRS for token creation to authenticate with other services.

==== <keycloak-jwkset-uri>
The URL of the Keycloak JWK Set. Used by the IRS to validate tokens when the IRS API is called.

==== <grafana-url>
The hostname where Grafana will be made available.

==== <edc-controlplane-endpoint-data>
The EDC consumer controlplane endpoint URL for data management, including the protocol.
If left empty, this defaults to the internal endpoint of the controlplane provided by the irs-edc-consumer Helm chart.


== EDC consumer configuration
If you want to provide your own EDC consumer, add the following entries to your values.yaml:

[source,yaml]
----
include::../../../../charts/edc-consumer/values.yaml[]
----

=== Values explained
EDC requires a DAPS instance to function correctly. For more information on this, please refer to the https://github.com/catenax-ng/product-DAPS[DAPS] or the https://github.com/catenax-ng/product-edc[EDC] documentation.

==== <controlplane-url>
The hostname where the EDC consumer controlplane will be made available.

==== <dataplane-url>
The hostname where the EDC consumer dataplane will be made available.

==== <vault-url>
The base URL of the Vault instance.
EDC requires a running instance of HashiCorp Vault to store the DAPS certificate and private key.

==== <vault-secret-store-path>
The path to the secret store in Vault where the DAPS certificate and key can be found.

_Example: /v1/team-name_

==== <daps-certificate-name>
The name of the DAPS certificate in the Vault.

_Example: irs-daps-certificate_

==== <daps-privatekey-name>
The name of the DAPS private key in the Vault.

_Example: irs-daps-private-key_

==== <daps-client-id>
The DAPS client ID.

==== <daps-jwks-url>
The URL of the DAPS JWK Set.

_Example: https://daps-hostname/.well-known/jwks.json_

==== <daps-token-url>
The URL of the DAPS token API.

_Example: https://daps-hostname/token_

== Secrets
This is a list of all secrets used in the deployment.

WARNING: Keep the values for these settings safe and do not publish them!

=== <postgres-admin-password>
Database password for the *postgres* user. To be defined by you.

=== <postgres-password>
Database password for the application user (default username: *edc*). To be defined by you.

=== <keycloak-client-id>
Client ID for Keycloak. Request this from your Keycloak operator.

=== <keycloak-client-secret>
Client secret for Keycloak. Request this from your Keycloak operator.

=== <minio-username>
Login username for Minio. To be defined by you.

=== <minio-password>
Login password for Minio. To be defined by you.

=== <edc-api-key>
An API key for the EDC API. To be defined by you.

=== <vault-token>
The access token for the HashiCorp Vault API.

=== <grafana-username>
Login username for Grafana. To be defined by you.

=== <grafana-password>
Login password for Grafana. To be defined by you.
