= Installation

The IRS Helm repository can be found here:
https://eclipse-tractusx.github.io/item-relationship-service/index.yaml

Use the latest release of the "irs-helm" chart.
It contains all required dependencies.

If you also want to set up your own EDC consumer, use the "irs-edc-consumer" chart.

Supply the required configuration properties (see chapter xref:configuration.adoc#_configuration[Configuration]) in a values.yaml file or override the settings directly.

== Deployment using Helm

Add the IRS Helm repository:

[listing]
$ helm repo add irs https://eclipse-tractusx.github.io/item-relationship-service

Then install the Helm chart into your cluster:

[listing]
$ helm install -f your-values.yaml irs-app irs/irs-helm

== Deployment using ArgoCD

Create a new Helm chart and use the IRS as a dependency.

[source,yaml]
----
dependencies:
  - name: irs-helm
    repository: https://eclipse-tractusx.github.io/item-relationship-service
    version: 5.x.x
  - name: irs-edc-consumer # optional
    repository: https://eclipse-tractusx.github.io/item-relationship-service
    version: 1.x.x

----

Then provide your configuration as the values.yaml of that chart.

Create a new application in ArgoCD and point it to your repository / Helm chart folder.
