= Troubleshooting

== Proxy support

If you are using an HTTP(S) proxy for outgoing connections, you need to configure the IRS to use it.

----
JAVA_TOOL_OPTIONS=-Dhttps.proxyHost=X.X.X.X -Dhttps.proxyPort=XXXX
----

You might need to specify both `http` and `https` options, depending on your configuration.

If your proxy is requiring authentication, you can use the `.proxyUser` and `.proxyPassword` properties in addition.

== Troubleshooting FAQ

=== Minio

==== Error: "The specified bucket does not exist"

IRS tries to read data from or write to the Minio storage, but no bucket exists. This can happen if Minio is running without a persistent volume and restarts, thus losing all data.
It can also happen if the persistent volume claim is deleted / recreated.

*Proposed solution steps:*

1. Make sure Minio is configured and running correctly.
2. Restart the IRS - this will recreate the missing bucket automatically.

=== Different Job model versions maintenance

Currently, the IRS only supports one version of the Job model at a time. This means that if the Job model is changed in a newer IRS version, old models stored in minio will no longer be supported and returned from IRS endpoints. The IRS application will work as usual, old versions of Job can stay in Minio and don't need to be removed - the IRS will simply ignore them. If you want to clear the minio from old models, the only way to achieve that is to delete them all and register new Jobs.