openapi: 3.0.1
info:
  description: API to retrieve parts tree information. See <a href="https://confluence.catena-x.net/display/CXM/PRS+Environments+and+Test+Data">this
    page</a> for more information on test data available in this environment.
  title: Catena-X Parts Relationship Service
  version: v0.1
servers:
- url: http://localhost:8080
paths:
  /api/v0.1/parts/{oneIDManufacturer}/{objectIDManufacturer}/partsTree:
    get:
      operationId: getPartsTreeByOneIdAndObjectId
      parameters:
      - description: Readable ID of manufacturer including plant
        in: path
        name: oneIDManufacturer
        required: true
        schema:
          type: string
          maxLength: 10000
          minLength: 1
      - description: "Unique identifier of a single, unique physical (sub)component/part/batch,\
          \ given by its manufacturer"
        in: path
        name: objectIDManufacturer
        required: true
        schema:
          type: string
          maxLength: 10000
          minLength: 1
      - description: PartsTree View to retrieve
        in: query
        name: view
        required: true
        schema:
          type: string
          description: View defining which data of the PartsTree is retrieved.
          enum:
          - AS_BUILT
          - AS_MAINTAINED
      - description: Aspect information to add to the returned tree
        example: CE
        in: query
        name: aspect
        required: false
        schema:
          type: string
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
      - description: "Max depth of the returned tree, if empty max depth is returned"
        in: query
        name: depth
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartRelationshipsWithInfos'
          description: Parts tree for a part
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
      summary: Get a PartsTree for a part
      tags:
      - Parts Relationship Service
  /api/v0.1/vins/{vin}/partsTree:
    get:
      operationId: getPartsTreeByVin
      parameters:
      - description: Vehicle Identification Number
        in: path
        name: vin
        required: true
        schema:
          type: string
          maxLength: 17
          minLength: 17
      - description: PartsTree View to retrieve
        in: query
        name: view
        required: true
        schema:
          type: string
          description: View defining which data of the PartsTree is retrieved.
          enum:
          - AS_BUILT
          - AS_MAINTAINED
      - description: Aspect information to add to the returned tree
        example: CE
        in: query
        name: aspect
        required: false
        schema:
          type: string
          maxLength: 10000
          minLength: 1
          pattern: ^(?!\s*$).+
      - description: "Max depth of the returned tree, if empty max depth is returned"
        in: query
        name: depth
        required: false
        schema:
          type: integer
          format: int32
          minimum: 1
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartRelationshipsWithInfos'
          description: Parts tree for a vehicle
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: A vehicle was not found with the given VIN
      summary: Get a PartsTree for a VIN
      tags:
      - Parts Relationship Service
components:
  schemas:
    Aspect:
      type: object
      description: Aspect location data
      properties:
        name:
          type: string
          description: Aspect name
          example: CE
          maxLength: 10000
          minLength: 1
        url:
          type: string
          format: url
          description: URL location of aspect data
          example: http://aspects-url/CE
          maxLength: 10000
          minLength: 1
      required:
      - name
      - url
    ErrorResponse:
      type: object
      description: Error response
      properties:
        errors:
          type: array
          description: List of errors
          items:
            type: string
            description: List of errors
        message:
          type: string
          description: Error message
        statusCode:
          type: string
          description: Error code
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
    PartId:
      type: object
      description: Unique part identifier
      properties:
        objectIDManufacturer:
          type: string
          description: "Unique identifier of a single, unique physical (sub)component/part/batch,\
            \ given by its manufacturer. For a vehicle, the Vehicle Identification\
            \ Number (VIN)."
          maxLength: 10000
          minLength: 1
        oneIDManufacturer:
          type: string
          description: Readable ID of manufacturer including plant
          maxLength: 10000
          minLength: 1
      required:
      - objectIDManufacturer
      - oneIDManufacturer
    PartInfo:
      type: object
      description: Information about parts
      properties:
        aspects:
          type: array
          description: List of aspect locations.
          items:
            $ref: '#/components/schemas/Aspect'
        part:
          $ref: '#/components/schemas/PartId'
        partTypeName:
          type: string
          description: "Type of material, (sub)component/part or vehicle. May not\
            \ be set."
          example: gearbox
      required:
      - part
    PartRelationship:
      type: object
      description: Link between two parts.
      properties:
        child:
          $ref: '#/components/schemas/PartId'
        parent:
          $ref: '#/components/schemas/PartId'
      required:
      - child
      - parent
    PartRelationshipsWithInfos:
      type: object
      description: List of relationships with information about parts.
      properties:
        partInfos:
          type: array
          description: List of part infos
          items:
            $ref: '#/components/schemas/PartInfo'
        relationships:
          type: array
          description: List of the relationships
          items:
            $ref: '#/components/schemas/PartRelationship'
