name: "Check if CHANGELOG file was modified in PR"

on:
  pull_request:
    branches: main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '.config/**'
      - 'docs/**'
      - 'local/**'

env:
  # Specific CHANGELOG file which is used for releasing the product. Default <CHANGELOG.md>.
  CHANGELOG_PATH: 'CHANGELOG.md'
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    name: changelog-check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check if CHANGELOG file was changed
        id: changelog-changed
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            ${{ env.CHANGELOG_PATH }}

      - name: Echo result if CHANGELOG file was changed
        if: steps.changelog-changed.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changelog-changed.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Find previous comment in PR
        if: steps.changelog-changed.outputs.any_changed == 'false'
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: CHANGELOG file was not updated! Make sure to include important changes.

      - name: Create or update comment in PR
        if: steps.changelog-changed.outputs.any_changed == 'false'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            CHANGELOG file was not updated! Make sure to include important changes.
          edit-mode: replace
