name: IRS Cucumber Integration Test execution

on:
  workflow_call: # Trigger by another workflow
    secrets:
      regularUserApiKey:
        required: true
      adminUserApiKey:
        required: true
      cucumberPublishToken:
        required: true
    inputs:
      executionFilter:
        required: true
        type: string

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests with Maven
        env:
          REGULAR_USER_API_KEY: ${{ secrets.regularUserApiKey }}
          ADMIN_USER_API_KEY: ${{ secrets.adminUserApiKey }}
          ISSUE_FILTER: ${{ inputs.executionFilter }}
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.cucumberPublishToken }}
        run: |
          # workaround replacement since injecting the token via environment variable does not work
          sed -i "s/CUCUMBER_TOKEN_IRS_PLACEHOLDER/${CUCUMBER_PUBLISH_TOKEN}/g" irs-cucumber-tests/src/test/java/org/eclipse/tractusx/irs/cucumber/RunCucumberTest.java

          mvn clean verify -P cucumber -Dgroups="$ISSUE_FILTER" -pl irs-cucumber-tests -am --batch-mode 2> irs-cucumber-tests/report-banner.txt

      - name: Publish Cucumber Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: |
            irs-cucumber-tests/target/cucumber-junit-report.xml

      - name: Get Cucumber Report
        if: always()
        id: get-cucumber-report
        run: |
          grep -E "^│.*│$" irs-cucumber-tests/report-banner.txt > irs-cucumber-tests/cucumber-report.txt
          sed -i 's/│//g' irs-cucumber-tests/cucumber-report.txt
          cat irs-cucumber-tests/cucumber-report.txt
          cat irs-cucumber-tests/cucumber-report.txt >> $GITHUB_STEP_SUMMARY

      - name: Find previous comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'View your Cucumber Report at'

      - name: Create or update comment in PR
        if: always() && github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'irs-cucumber-tests/cucumber-report.txt'
          edit-mode: replace

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: 'irs-cucumber-tests/target/report.html'
