name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.27.3'
        required: false
        type: string
  workflow_call: # Trigger by another workflow
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        default: 'kindest/node:v1.27.3'
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e # v2
        with:
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}
          version: v0.20.0

      - name: Build image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          push: true
          tags: kind-registry:5000/irs-api:testing

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          version: v3.9.3

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
             echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --validate-maintainers=false --check-version-increment=false --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (install)
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add minio https://charts.min.io/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          ct install --charts charts/item-relationship-service --helm-extra-set-args "--set=image.tag=testing --set=image.repository=kind-registry:5000/irs-api"
        if: steps.list-changed.outputs.changed == 'true'
