name: Integration testdata setup

on:
  workflow_dispatch:
    inputs:
      testfilePath:
        description: 'Path to Testdata file on GitHub'
        required: true
        type: string
      submodelUrls:
        description: 'Space-separated list of Submodel server URLs'
        required: true
        type: string
      aasUrl:
        description: 'Digital twin registry URL'
        required: true
        type: string
      edcUrls:
        description: 'Space-separated list of Provider control plane URLs'
        required: true
        type: string
      edcApiKey:
        description: 'API-Key for the provider control plane'
        required: true
        type: string
      esrUrl:
        description: 'ESR endpoint Url'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 #install the python needed
          cache: 'pip'
      - run: pip install -r local/testing/testdata/requirements.txt

      - name: Delete existing and setup new test data on provider EDC and Registry
        if: ${{ github.event.inputs.esrUrl == '' }}
        env:
          TESTFILE_PATH: ${{ github.event.inputs.testfilePath }}
          SUBMODEL_URLs: ${{ github.event.inputs.submodelUrls }}
          AAS_URL: ${{ github.event.inputs.aasUrl }}
          EDC_URLs: ${{ github.event.inputs.edcUrls }}
          EDC_API_KEY: ${{ github.event.inputs.edcApiKey }}
        run: |
          python local/testing/testdata/reset-env.py \
          -a $AAS_URL \
          -edc $EDC_URLs \
          -k $EDC_API_KEY
          python local/testing/testdata/transform-and-upload.py \
          -f $TESTFILE_PATH \
          -s $SUBMODEL_URLs \
          -a $AAS_URL \
          -edc $EDC_URLs \
          -k $EDC_API_KEY

      - name: Delete existing and setup new test data on provider EDC and Registry
        if: ${{ github.event.inputs.esrUrl != '' }}
        env:
          TESTFILE_PATH: ${{ github.event.inputs.testfilePath }}
          SUBMODEL_URLs: ${{ github.event.inputs.submodelUrls }}
          AAS_URL: ${{ github.event.inputs.aasUrl }}
          EDC_URLs: ${{ github.event.inputs.edcUrls }}
          EDC_API_KEY: ${{ github.event.inputs.edcApiKey }}
          ESR_URL: ${{ github.event.inputs.esrUrl }}
        run: |
          python local/testing/testdata/reset-env.py \
          -a $AAS_URL \
          -edc $EDC_URLs \
          -k $EDC_API_KEY
          python local/testing/testdata/transform-and-upload.py \
          -f $TESTFILE_PATH \
          -s $SUBMODEL_URLs \
          -a $AAS_URL \
          -edc $EDC_URLs \
          -k $EDC_API_KEY
          -e $ESR_URL 
