name: IRS INT Cucumber Integration test execution

on:
  workflow_dispatch: # Trigger manually

jobs:
  trigger-integration-test:
    uses: ./.github/workflows/xray-cucumber-integration.yaml
    secrets:
      regularUserApiKey: ${{ secrets.INT_REGULAR_USER_API_KEY }}
      adminUserApiKey: ${{ secrets.INT_ADMIN_USER_API_KEY }}
      jiraUser: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
      jiraPassword: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
    with:
      executionFilter: "not @Ignore and @INTEGRATION_TEST and @INT"
      exportFilter: "11349"

