name: "Validate OpenAPI definition"

on:
  workflow_dispatch: # Trigger manually
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@264fd875d3c6e1bf65da1f0a63e095cbe41ffef3 # v1
        with:
          definition-file: docs/src/api/irs-api.yaml
