name: "Validate OpenAPI definition"

on:
  workflow_dispatch: # Trigger manually
  workflow_call:
    inputs:
      ref-to-check-out:
        description: 'Ref of branch/tag from which to execute workflow'
        required: true
        type: string
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          ref: ${{ inputs.ref-to-check-out || github.ref }}

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: docs/src/api/irs-api.yaml
