name: "Validate OpenAPI definition"

on:
  workflow_dispatch: # Trigger manually
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  test_swagger_editor_validator_remote:
    runs-on: ubuntu-latest
    name: Swagger Editor Validator Remote

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@v1
        with:
          definition-file: docs/src/api/irs-api.yaml
